<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Consultation History | CLSU Infirmary Telemedicine System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root{--ink:#071438;--muted:#4e5b86;--green:#087d32;--green-dark:#006824;--line:#e1e7ef;--page:#fbfcfa;--blue:#2578e7;--orange:#ff8a00;--purple:#087d32;--red:#f52222;--shadow:0 12px 30px rgba(24,39,75,.07)}
        *{box-sizing:border-box}body{min-height:100vh;margin:0;color:var(--ink);font-family:"Inter","Segoe UI",system-ui,-apple-system,BlinkMacSystemFont,sans-serif;background:radial-gradient(circle at 88% 92%,rgba(255,211,67,.26),transparent 16rem),linear-gradient(180deg,#fbfdfb 0%,#f7faf5 100%)}a{color:inherit;text-decoration:none}button,input,select{font:inherit}
        .app-shell{display:grid;grid-template-columns:300px minmax(0,1fr);min-height:100vh;transition:grid-template-columns .2s ease}.sidebar{position:sticky;top:0;height:100vh;padding:1.55rem 1.25rem;border-right:1px solid var(--line);background:#fff;box-shadow:8px 0 28px rgba(24,39,75,.04);overflow-y:auto;transition:padding .2s ease}.brand{display:flex;align-items:center;gap:.85rem;margin-bottom:2.35rem}.brand img{width:62px;height:62px;border-radius:50%;object-fit:cover}.brand strong{display:block;font-size:1.42rem;font-weight:950;line-height:1.05}.brand span{color:#111;font-size:1.05rem;font-weight:800}
        .avatar,.mini-avatar{display:grid;place-items:center;border-radius:50%;color:#fff;background:linear-gradient(135deg,#d29a82 0%,#4a4865 100%);overflow:hidden}.avatar{width:64px;height:64px;border:1px solid #d4dbe7;font-size:1.85rem}.mini-avatar{width:46px;height:46px;font-size:1.25rem}.nurse-mini{display:grid;grid-template-columns:64px minmax(0,1fr);align-items:center;gap:.9rem;margin-bottom:1.6rem}.nurse-mini h2{margin:0 0 .18rem;font-size:1rem;font-weight:950}.nurse-mini p{margin:0 0 .25rem;color:var(--muted);font-size:.9rem}.online{display:inline-flex;align-items:center;gap:.38rem;color:#2d405f;font-size:.82rem}.online:before{content:"";width:10px;height:10px;border-radius:50%;background:var(--green)}
        .sidebar-collapse{display:flex;align-items:center;justify-content:center;gap:.55rem;width:100%;min-height:42px;margin:0 0 1rem;border:1px solid #d7e0ee;border-radius:9px;color:var(--green-dark);background:#fff;font-weight:950}.nav-list{display:grid;gap:.52rem;margin:0;padding:0;list-style:none}.nav-link{position:relative;display:flex;align-items:center;gap:1rem;min-height:54px;padding:.75rem .95rem;border-radius:10px;color:#1d293f;font-weight:850}.nav-link i{width:28px;color:#5d697d;font-size:1.35rem}.nav-link.active{color:var(--green-dark);background:linear-gradient(90deg,#e7f4e6,#f5faf3)}.nav-link.active i{color:var(--green)}.nav-badge{display:grid;place-items:center;min-width:24px;height:24px;margin-left:auto;padding:0 .38rem;border-radius:999px;color:#fff;background:var(--green);font-size:.78rem;font-weight:950}.logout-link{margin-top:6.5rem}
        body.sidebar-collapsed .app-shell{grid-template-columns:88px minmax(0,1fr)}body.sidebar-collapsed .sidebar{padding-inline:.75rem;overflow-x:hidden}body.sidebar-collapsed .brand{justify-content:center;gap:0;margin-bottom:1.5rem}body.sidebar-collapsed .brand span,body.sidebar-collapsed .nurse-mini > div:last-child,body.sidebar-collapsed .sidebar-collapse span{display:none}body.sidebar-collapsed .brand img,body.sidebar-collapsed .avatar{width:48px;height:48px}body.sidebar-collapsed .nurse-mini{grid-template-columns:1fr;justify-items:center;margin-bottom:1rem}body.sidebar-collapsed .sidebar-collapse{width:48px;margin-inline:auto}body.sidebar-collapsed .nav-link{justify-content:center;gap:0;padding-inline:.6rem;font-size:0}body.sidebar-collapsed .nav-link i{width:auto;font-size:1.45rem}body.sidebar-collapsed .nav-badge{position:absolute;top:5px;right:4px;min-width:18px;height:18px;margin-left:0;padding:0 .25rem;font-size:.62rem}body.sidebar-collapsed .logout-link{margin-top:2rem}
        .main{min-width:0;padding:1.45rem 1.6rem}.topbar{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:start;gap:1.2rem;margin-bottom:1.35rem}.page-title h1{margin:0 0 .45rem;font-size:clamp(1.8rem,2.35vw,2.4rem);font-weight:950}.page-title p{margin:0;color:#34426f}.bell{position:relative;display:grid;place-items:center;width:48px;height:48px;border:0;background:transparent;color:#172447;font-size:1.6rem}.bell span{position:absolute;top:0;right:0;display:grid;place-items:center;width:24px;height:24px;border-radius:50%;color:#fff;background:#e60012;font-size:.75rem;font-weight:950}.nurse-top{display:grid;grid-template-columns:48px auto 24px;align-items:center;gap:.75rem;padding-left:1rem;border-left:1px solid var(--line)}.nurse-top .avatar{width:48px;height:48px;font-size:1.35rem}.nurse-top strong{display:block;font-weight:950}.nurse-top span{font-size:.82rem;color:#26335f}
        .panel,.stat-card{border:1px solid var(--line);border-radius:10px;background:#fff;box-shadow:var(--shadow)}.toolbar{display:grid;grid-template-columns:minmax(260px,1.2fr) repeat(3,minmax(150px,.65fr)) minmax(230px,.9fr) auto;gap:.85rem;margin-bottom:1rem;padding:1rem}.search-box{position:relative}.field,.select-btn,.export-btn{height:44px;border:1px solid #d7e0ee;border-radius:7px;background:#fff;color:#071438}.field{width:100%;padding:0 2.7rem 0 1rem}.search-box i{position:absolute;right:.9rem;top:50%;transform:translateY(-50%);color:#172447;font-size:1.2rem}.select-btn,.export-btn{display:flex;align-items:center;justify-content:center;gap:.6rem;padding:0 1rem;font-weight:950}.export-btn{color:#5b22db;border-color:#9eddb4}
        .stats-grid{display:grid;grid-template-columns:repeat(4,minmax(160px,1fr));gap:1rem;margin-bottom:1rem}.stat-card{display:grid;grid-template-columns:58px minmax(0,1fr);align-items:center;gap:1rem;min-height:104px;padding:1rem}.stat-icon{display:grid;place-items:center;width:52px;height:52px;border-radius:9px;color:#087d32;background:#e9f5e9;font-size:1.7rem}.stat-icon.green{color:var(--green-dark);background:#e9f5e9}.stat-icon.orange{color:#f27900;background:#fff0df}.stat-icon.blue{color:#1f73e8;background:#eaf3ff}.stat-card small{display:block;font-weight:950}.stat-card strong{display:block;font-size:1.75rem;font-weight:950;line-height:1.05}.trend{font-size:.82rem;font-weight:950}.trend.up{color:var(--green)}.trend.down{color:#f27900}
        .content-grid{display:grid;grid-template-columns:minmax(0,1fr) 380px;gap:1rem}.history-panel{overflow:hidden}.table-wrap{overflow-x:auto}.history-table{width:100%;min-width:900px;border-collapse:collapse}.history-table th,.history-table td{padding:1rem;border-bottom:1px solid #edf1f7;text-align:left;vertical-align:middle;font-size:.88rem}.history-table th{color:#34426f;background:#fff;font-weight:950}.history-table tr.selected{background:#f3fbf5;box-shadow:inset 0 0 0 1px #d5c4ff}.patient-cell{display:grid;grid-template-columns:46px minmax(0,1fr);gap:.75rem;align-items:center}.patient-cell strong{display:block}.muted{color:#34426f}.type{display:inline-flex;align-items:center;gap:.4rem}.type.chat{color:#006824}.type.follow{color:#f27900}.triage{font-weight:950}.triage.l1,.triage.l2{color:#f52222}.triage.l3{color:#ff7500}.triage.l4{color:var(--green-dark)}.status{display:inline-grid;place-items:center;width:max-content;padding:.25rem .55rem;border:1px solid #9eddb4;border-radius:6px;color:var(--green-dark);background:#eefaef;font-size:.76rem;font-weight:950}.status.purple{color:#087d32;border-color:#d5c4ff;background:#f5f0ff}.view-btn{display:inline-flex;align-items:center;justify-content:center;gap:.45rem;min-width:76px;height:34px;border:1px solid #9eddb4;border-radius:7px;color:#5b22db;background:#fff;font-weight:950}
        .pager{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem;color:#34426f;font-size:.84rem}.pages{display:flex;gap:.35rem}.page-btn{display:grid;place-items:center;min-width:34px;height:34px;border:1px solid #d7e0ee;border-radius:7px;background:#fff;color:#071438;font-weight:950}.page-btn.active{color:#fff;background:var(--purple);border-color:var(--purple)}
        .detail-panel{overflow:hidden}.detail-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.2rem;border-bottom:1px solid var(--line);background:#f3fbf5}.detail-head h2{margin:0;color:#5b22db;font-size:1.2rem;font-weight:950}.detail-body{display:grid;gap:1rem;padding:1.2rem}.detail-patient{display:grid;grid-template-columns:64px minmax(0,1fr);gap:1rem;align-items:center}.detail-patient .mini-avatar{width:64px;height:64px}.detail-patient h3{margin:0 0 .3rem;font-size:1.05rem;font-weight:950}.detail-list{display:grid;gap:.9rem;padding-top:.8rem;border-top:1px solid var(--line)}.detail-row{display:grid;grid-template-columns:24px 110px minmax(0,1fr);gap:.6rem;color:#071438;font-size:.88rem}.detail-row i{color:#5b22db}.detail-row span:nth-child(2){color:#34426f;font-weight:850}.notes{line-height:1.6}.action-stack{display:grid;gap:.7rem;margin-top:1rem}.primary-btn,.secondary-btn{display:flex;align-items:center;justify-content:center;gap:.6rem;min-height:48px;border-radius:8px;font-weight:950}.primary-btn{border:0;color:#fff;background:linear-gradient(90deg,#087d32,#087d32)}.secondary-btn{border:1px solid #9eddb4;color:#5b22db;background:#fff}.notice{margin-top:1rem;padding:1rem 1.2rem;border:1px solid #ded1ff;border-radius:8px;color:#321484;background:#f3fbf5}.menu-toggle,.sidebar-overlay{display:none}
        @media(max-width:1450px){.toolbar{grid-template-columns:1fr 1fr 1fr}.toolbar .search-box{grid-column:1/-1}.toolbar .export-btn{grid-column:auto}.stats-grid{grid-template-columns:repeat(3,1fr)}.content-grid{grid-template-columns:1fr}.detail-panel{order:-1}}
        @media(max-width:1180px){.app-shell,body.sidebar-collapsed .app-shell{grid-template-columns:1fr}.sidebar-collapse{display:none}.menu-toggle{position:fixed;top:1rem;left:1rem;z-index:1100;display:grid;place-items:center;width:48px;height:48px;border:1px solid var(--line);border-radius:12px;color:var(--green-dark);background:#fff;box-shadow:0 10px 24px rgba(24,39,75,.12);font-size:1.55rem}.sidebar-overlay{position:fixed;inset:0;z-index:1050;display:block;background:rgba(7,20,56,.42);opacity:0;pointer-events:none;transition:opacity .2s ease}body.sidebar-open .sidebar-overlay{opacity:1;pointer-events:auto}.sidebar{position:fixed;inset:0 auto 0 0;z-index:1060;width:min(84vw,310px);height:100vh;transform:translateX(-100%);transition:transform .24s ease;box-shadow:12px 0 36px rgba(7,20,56,.18)}body.sidebar-open .sidebar{transform:translateX(0)}.main{padding-top:5rem}}
        @media(max-width:760px){.main{padding-inline:1rem}.topbar,.toolbar,.stats-grid{grid-template-columns:1fr}.nurse-top{display:none}.content-grid{display:block}.detail-panel{margin-bottom:1rem}.pager{align-items:flex-start;flex-direction:column}.detail-row{grid-template-columns:24px minmax(0,1fr)}.detail-row strong{grid-column:2}.toolbar .search-box{grid-column:auto}}
    </style>
</head>
<body>
    <button class="menu-toggle" type="button" aria-label="Open navigation" aria-controls="nurseSidebar" aria-expanded="false"><i class="bi bi-list"></i></button>
    <div class="app-shell">
        <aside class="sidebar" id="nurseSidebar">
            <a class="brand" href="dashboard.php"><img src="../auth/assets/img/CLSU_Logo.jpg" alt="CLSU logo"><span><strong>CLSU Infirmary</strong>Telemedicine System</span></a>
            <div class="nurse-mini"><div class="avatar" aria-hidden="true"><i class="bi bi-person-fill"></i></div><div><h2>Nurse Ana Reyes</h2><p>Registered Nurse</p><span class="online">Online</span></div></div>
            <button class="sidebar-collapse" type="button" aria-label="Collapse sidebar" aria-expanded="true"><i class="bi bi-layout-sidebar-inset"></i><span>Collapse</span></button>
            <nav aria-label="Nurse navigation">
                <ul class="nav-list">
                    <li><a class="nav-link" href="dashboard.php"><i class="bi bi-house-door"></i> Dashboard</a></li>
                    <li><a class="nav-link" href="consultationinbox.php"><i class="bi bi-inbox"></i> Consultation Inbox <span class="nav-badge">12</span></a></li>
                    <li><a class="nav-link" href="activeconsult.php"><i class="bi bi-chat-dots"></i> Active Consultations <span class="nav-badge">3</span></a></li>
                    <li><a class="nav-link" href="followup.php"><i class="bi bi-calendar2-check"></i> Follow-up Requests <span class="nav-badge">8</span></a></li>
                    <li><a class="nav-link" href="patientdirect.php"><i class="bi bi-people"></i> Patient Directory</a></li>
                    <li><a class="nav-link active" href="consulthistory.php"><i class="bi bi-clock-history"></i> Consultation History</a></li>
                    <li><a class="nav-link" href="notif.php"><i class="bi bi-bell"></i> Notifications <span class="nav-badge">4</span></a></li>
                    <li><a class="nav-link" href="profile.php"><i class="bi bi-person-badge"></i> Profile</a></li>
                </ul>
            </nav>
            <a class="nav-link logout-link" href="../auth/index.php"><i class="bi bi-box-arrow-right"></i> Logout</a>
        </aside>

        <main class="main">
            <header class="topbar">
                <div class="page-title"><h1>Consultation History</h1><p>View your handled consultations and related details.</p></div>
                <button class="bell" type="button" aria-label="Notifications"><i class="bi bi-bell"></i><span>6</span></button>
                <div class="nurse-top"><span class="avatar"><i class="bi bi-person-fill"></i></span><div><strong>Nurse Ana Reyes</strong><span>Registered Nurse</span></div><i class="bi bi-chevron-down"></i></div>
            </header>

            <section class="panel toolbar" aria-label="History filters">
                <label class="search-box"><input class="field" type="search" placeholder="Search patient name, ID, or concern..."><i class="bi bi-search"></i></label>
                <button class="select-btn">All Types <i class="bi bi-chevron-down"></i></button>
                <button class="select-btn">All Statuses <i class="bi bi-chevron-down"></i></button>
                <button class="select-btn">All Triage Levels <i class="bi bi-chevron-down"></i></button>
                <button class="select-btn"><i class="bi bi-calendar2"></i> May 10, 2025 - May 16, 2025 <i class="bi bi-chevron-down"></i></button>
                <button class="export-btn"><i class="bi bi-download"></i> Export Summary</button>
            </section>

            <section class="stats-grid" aria-label="Consultation summary">
                <article class="stat-card"><span class="stat-icon"><i class="bi bi-stethoscope"></i></span><div><small>Total Consultations</small><strong>128</strong><span>Handled</span></div></article>
                <article class="stat-card"><span class="stat-icon green"><i class="bi bi-check-circle"></i></span><div><small>Completed</small><strong>96 <span class="trend up">+ 75%</span></strong></div></article>
                <article class="stat-card"><span class="stat-icon orange"><i class="bi bi-arrow-up"></i></span><div><small>Escalated</small><strong>18 <span class="trend down">- 14%</span></strong></div></article>
                <article class="stat-card"><span class="stat-icon blue"><i class="bi bi-people"></i></span><div><small>Follow-up</small><strong>27 <span class="trend up">+ 21%</span></strong></div></article>
            </section>

            <div class="content-grid">
                <section class="panel history-panel">
                    <div class="table-wrap">
                        <table class="history-table">
                            <thead><tr><th>Date &amp; Time <i class="bi bi-arrow-down-up"></i></th><th>Patient <i class="bi bi-arrow-down-up"></i></th><th>Type <i class="bi bi-arrow-down-up"></i></th><th>Triage Level</th><th>Status <i class="bi bi-arrow-down-up"></i></th><th>Outcome</th><th>Actions <i class="bi bi-arrow-down-up"></i></th></tr></thead>
                            <tbody>
                                <tr class="selected"><td>May 16, 2025<br><span class="muted">10:20 AM</span></td><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Maria Dela Cruz</strong><span>2025-00123</span></div></div></td><td><span class="type chat"><i class="bi bi-chat-dots"></i> Chat Consultation</span></td><td><span class="triage l2">Level 2<br>Urgent</span></td><td><span class="status">Completed</span><br><span class="muted">10:45 AM</span></td><td>Advice Given</td><td><a class="view-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View</a></td></tr>
                                <tr><td>May 16, 2025<br><span class="muted">09:45 AM</span></td><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Juan Miguel Santos</strong><span>2025-00118</span></div></div></td><td><span class="type chat"><i class="bi bi-chat-dots"></i> Chat Consultation</span></td><td><span class="triage l3">Level 3<br>Moderate</span></td><td><span class="status">Completed</span><br><span class="muted">10:05 AM</span></td><td>Advice Given</td><td><a class="view-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View</a></td></tr>
                                <tr><td>May 15, 2025<br><span class="muted">04:15 PM</span></td><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Angela Reyes</strong><span>2025-00120</span></div></div></td><td><span class="type follow"><i class="bi bi-person-plus"></i> Follow-up Request</span></td><td><span class="triage l2">Level 2<br>Urgent</span></td><td><span class="status">Completed</span><br><span class="muted">04:35 PM</span></td><td>Symptoms Improved</td><td><a class="view-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View</a></td></tr>
                                <tr><td>May 15, 2025<br><span class="muted">02:30 PM</span></td><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Pedro Garcia</strong><span>2025-00115</span></div></div></td><td><span class="type chat"><i class="bi bi-chat-dots"></i> Chat Consultation</span></td><td><span class="triage l1">Level 1<br>Emergency</span></td><td><span class="status purple">Escalated</span><br><span class="muted">02:40 PM</span></td><td>Escalated to Physician</td><td><a class="view-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View</a></td></tr>
                                <tr><td>May 15, 2025<br><span class="muted">11:05 AM</span></td><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Katrina Lopez</strong><span>2025-00121</span></div></div></td><td><span class="type chat"><i class="bi bi-chat-dots"></i> Chat Consultation</span></td><td><span class="triage l4">Level 4<br>Non-urgent</span></td><td><span class="status">Completed</span><br><span class="muted">11:25 AM</span></td><td>Advice Given</td><td><a class="view-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View</a></td></tr>
                                <tr><td>May 14, 2025<br><span class="muted">03:10 PM</span></td><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Kevin Lopez</strong><span>2025-00125</span></div></div></td><td><span class="type chat"><i class="bi bi-chat-dots"></i> Chat Consultation</span></td><td><span class="triage l2">Level 2<br>Urgent</span></td><td><span class="status">Completed</span><br><span class="muted">03:30 PM</span></td><td>Referred to Clinic</td><td><a class="view-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View</a></td></tr>
                                <tr><td>May 14, 2025<br><span class="muted">10:25 AM</span></td><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Rhea Mae Villanueva</strong><span>2025-00130</span></div></div></td><td><span class="type chat"><i class="bi bi-chat-dots"></i> Chat Consultation</span></td><td><span class="triage l3">Level 3<br>Moderate</span></td><td><span class="status">Completed</span><br><span class="muted">10:50 AM</span></td><td>Advice Given</td><td><a class="view-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View</a></td></tr>
                                <tr><td>May 13, 2025<br><span class="muted">09:00 AM</span></td><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>John Paul Dela Cruz</strong><span>2025-00110</span></div></div></td><td><span class="type follow"><i class="bi bi-person-plus"></i> Follow-up Request</span></td><td><span class="triage l2">Level 2<br>Urgent</span></td><td><span class="status">Completed</span><br><span class="muted">09:15 AM</span></td><td>For Monitoring</td><td><a class="view-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View</a></td></tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="pager"><span>Showing 1 to 8 of 128 consultations</span><div class="pages"><button class="page-btn"><i class="bi bi-chevron-left"></i></button><button class="page-btn active">1</button><button class="page-btn">2</button><button class="page-btn">3</button><button class="page-btn">4</button><button class="page-btn">5</button><button class="page-btn">...</button><button class="page-btn">16</button><button class="page-btn"><i class="bi bi-chevron-right"></i></button></div></div>
                </section>

                <aside class="panel detail-panel">
                    <header class="detail-head"><h2>Consultation Detail</h2><button class="btn p-0" type="button" aria-label="Close detail"><i class="bi bi-x-lg"></i></button></header>
                    <div class="detail-body">
                        <div class="detail-patient"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><h3>Maria Dela Cruz <span class="status ms-2">Completed</span></h3><p class="mb-1">ID: 2025-00123</p><p class="mb-0 muted">20 yrs &bull; Female &bull; Student</p><button class="secondary-btn mt-2" style="min-height:34px;width:max-content;padding:0 .85rem"><i class="bi bi-person-badge"></i> View Patient Profile</button></div></div>
                        <div class="detail-list">
                            <div class="detail-row"><i class="bi bi-calendar2"></i><span>Date &amp; Time</span><strong>May 16, 2025 &bull; 10:20 AM</strong></div>
                            <div class="detail-row"><i class="bi bi-chat-dots"></i><span>Type</span><strong>Chat Consultation</strong></div>
                            <div class="detail-row"><i class="bi bi-arrow-up"></i><span>Triage Level</span><strong class="triage l2">Level 2 - Urgent</strong></div>
                            <div class="detail-row"><i class="bi bi-check2-circle"></i><span>Status</span><strong><span class="status">Completed</span><br>10:45 AM</strong></div>
                            <div class="detail-row"><i class="bi bi-person"></i><span>Handled By</span><strong>Nurse Ana Reyes</strong></div>
                            <div class="detail-row"><i class="bi bi-clipboard-pulse"></i><span>Chief Complaint</span><strong>Fever and cough for 2 days</strong></div>
                            <div class="detail-row"><i class="bi bi-check-square"></i><span>Outcome</span><strong>Advice Given</strong></div>
                            <div class="detail-row"><i class="bi bi-card-text"></i><span>Notes Summary</span><strong class="notes">Advised rest, increased fluids, and Paracetamol 500mg q8h as needed. Patient was advised to seek medical attention if symptoms persist.</strong></div>
                            <div class="detail-row"><i class="bi bi-clock"></i><span>Duration</span><strong>25 minutes</strong></div>
                        </div>
                        <div class="action-stack"><a class="primary-btn" href="consultationdetails.php"><i class="bi bi-eye"></i> View Full Consultation</a><button class="secondary-btn"><i class="bi bi-download"></i> Export This Record</button></div>
                    </div>
                </aside>
            </div>
            <div class="notice"><i class="bi bi-info-circle-fill me-2"></i>This history includes consultations that you have handled. Click "View" to see full details, notes, and communications.</div>
        </main>
    </div>
    <div class="sidebar-overlay" data-close-sidebar></div>
    <script>
        const menuToggle=document.querySelector(".menu-toggle");
        const sidebarCollapse=document.querySelector(".sidebar-collapse");
        const sidebarOverlay=document.querySelector(".sidebar-overlay");
        const sidebarLinks=document.querySelectorAll(".sidebar .nav-link,.sidebar .brand");
        const setSidebar=(isOpen)=>{document.body.classList.toggle("sidebar-open",isOpen);menuToggle.setAttribute("aria-expanded",String(isOpen));menuToggle.setAttribute("aria-label",isOpen?"Close navigation":"Open navigation")};
        menuToggle.addEventListener("click",()=>setSidebar(!document.body.classList.contains("sidebar-open")));
        const setSidebarCollapsed=(isCollapsed)=>{document.body.classList.toggle("sidebar-collapsed",isCollapsed);sidebarCollapse.setAttribute("aria-expanded",String(!isCollapsed));sidebarCollapse.setAttribute("aria-label",isCollapsed?"Expand sidebar":"Collapse sidebar");sidebarCollapse.querySelector("span").textContent=isCollapsed?"Expand":"Collapse"};
        sidebarCollapse.addEventListener("click",()=>setSidebarCollapsed(!document.body.classList.contains("sidebar-collapsed")));
        sidebarOverlay.addEventListener("click",()=>setSidebar(false));
        sidebarLinks.forEach((link)=>link.addEventListener("click",()=>setSidebar(false)));
        document.addEventListener("keydown",(event)=>{if(event.key==="Escape")setSidebar(false)});
    </script>
</body>
</html>
