<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Consultation History | CLSU Infirmary Telemedicine System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root{--ink:#071438;--muted:#4e5b86;--green:#087d32;--green-dark:#006824;--line:#dfe6f2;--page:#f6f9fd;--blue:#2578e7;--orange:#ff8a00;--purple:#7c3df0;--red:#f52222;--shadow:0 12px 30px rgba(24,39,75,.07)}
        *{box-sizing:border-box}body{min-height:100vh;margin:0;color:var(--ink);font-family:"Inter","Segoe UI",system-ui,-apple-system,BlinkMacSystemFont,sans-serif;background:linear-gradient(180deg,#fbfdfb 0%,#f6f9fd 100%)}a{color:inherit;text-decoration:none}button,input,select{font:inherit}
        .app-shell{display:grid;grid-template-columns:300px minmax(0,1fr);min-height:100vh;transition:grid-template-columns .2s ease}.sidebar{position:sticky;top:0;height:100vh;padding:1.55rem 1.25rem;border-right:1px solid var(--line);background:#fff;box-shadow:8px 0 28px rgba(24,39,75,.04);overflow-y:auto;transition:padding .2s ease}.brand{display:flex;align-items:center;gap:.85rem;margin-bottom:2.35rem}.brand img{width:62px;height:62px;border-radius:50%;object-fit:cover}.brand strong{display:block;color:var(--green-dark);font-size:1.35rem;font-weight:950;line-height:1.05}.brand span{display:block;color:var(--green-dark);font-size:1rem;font-weight:800}
        .avatar,.mini-avatar{display:grid;place-items:center;border-radius:50%;color:#fff;background:linear-gradient(145deg,#f3b79b,#253055);overflow:hidden}.avatar{width:64px;height:64px;border:1px solid #d4dbe7;font-size:1.85rem}.mini-avatar{width:46px;height:46px;font-size:1.2rem}.mini-avatar.male{background:linear-gradient(145deg,#f0b08f,#39415d)}.physician-mini{display:grid;grid-template-columns:64px minmax(0,1fr);align-items:center;gap:.9rem;margin-bottom:1.6rem}.physician-mini h2{margin:0 0 .18rem;font-size:1rem;font-weight:950}.physician-mini p{margin:0 0 .25rem;color:var(--muted);font-size:.9rem}.online{display:inline-flex;align-items:center;gap:.38rem;color:#2d405f;font-size:.82rem}.online:before{content:"";width:10px;height:10px;border-radius:50%;background:var(--green)}
        .sidebar-collapse{display:flex;align-items:center;justify-content:center;gap:.55rem;width:100%;min-height:42px;margin:0 0 1rem;border:1px solid #d7e0ee;border-radius:9px;color:var(--green-dark);background:#fff;font-weight:950}.nav-list{display:grid;gap:.45rem;margin:0;padding:0 0 1.4rem;border-bottom:1px solid var(--line);list-style:none}.nav-secondary{display:grid;gap:.45rem;margin:1.25rem 0 1.6rem;padding:0;list-style:none}.nav-link{position:relative;display:flex;align-items:center;gap:1rem;min-height:56px;padding:.8rem .95rem;border-radius:10px;color:#1d293f;font-weight:850}.nav-link:before{content:"";position:absolute;left:-1.25rem;width:8px;height:44px;border-radius:0 8px 8px 0;background:transparent}.nav-link i{width:28px;color:#5d697d;font-size:1.35rem}.nav-link.active{color:var(--green-dark);background:linear-gradient(90deg,#e7f4e6,#f5faf3)}.nav-link.active:before{background:var(--green)}.nav-link.active i{color:var(--green)}.nav-badge{display:grid;place-items:center;min-width:24px;height:24px;margin-left:auto;padding:0 .4rem;border-radius:999px;color:#fff;background:var(--green);font-size:.76rem;font-weight:950}.campus-card{margin:1.4rem 0 1.2rem;padding:1.2rem;border:1px solid #dcebdd;border-radius:10px;background:linear-gradient(145deg,#eef8ef,#f8fcf8);color:var(--green-dark)}.campus-art{height:76px;margin-bottom:.8rem;opacity:.55;background:linear-gradient(180deg,transparent 55%,#2c7141 0);clip-path:polygon(0 76%,12% 62%,18% 65%,24% 30%,31% 66%,48% 50%,58% 66%,72% 46%,84% 62%,100% 70%,100% 100%,0 100%)}.campus-card h3{margin:0 0 .55rem;font-size:1.25rem;font-weight:950}.campus-card p{margin:0;font-style:italic}.logout-link{margin-top:1rem}
        body.sidebar-collapsed .app-shell{grid-template-columns:88px minmax(0,1fr)}body.sidebar-collapsed .sidebar{padding-inline:.75rem;overflow-x:hidden}body.sidebar-collapsed .brand{justify-content:center;gap:0;margin-bottom:1.5rem}body.sidebar-collapsed .brand span,body.sidebar-collapsed .physician-mini > div:last-child,body.sidebar-collapsed .sidebar-collapse span,body.sidebar-collapsed .campus-card{display:none}body.sidebar-collapsed .brand img,body.sidebar-collapsed .avatar{width:48px;height:48px}body.sidebar-collapsed .physician-mini{grid-template-columns:1fr;justify-items:center;margin-bottom:1rem}body.sidebar-collapsed .sidebar-collapse{width:48px;margin-inline:auto}body.sidebar-collapsed .nav-link{justify-content:center;gap:0;padding-inline:.6rem;font-size:0}body.sidebar-collapsed .nav-link i{width:auto;font-size:1.45rem}body.sidebar-collapsed .nav-badge{position:absolute;top:5px;right:4px;min-width:18px;height:18px;margin-left:0;padding:0 .25rem;font-size:.62rem}
        .main{min-width:0;padding:1.55rem 1.65rem 0}.topbar{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:start;gap:1.2rem;margin-bottom:1.25rem}.topbar:after{content:"";position:absolute;left:38%;top:-1.25rem;width:min(520px,34vw);height:122px;opacity:.18;background:linear-gradient(180deg,transparent 52%,#2c7141 0);clip-path:polygon(0 74%,13% 58%,20% 61%,25% 33%,31% 61%,47% 41%,58% 64%,72% 43%,84% 60%,100% 68%,100% 100%,0 100%);pointer-events:none}.page-title{position:relative;z-index:1}.page-title h1{margin:0 0 .55rem;font-size:clamp(1.9rem,2.7vw,2.65rem);font-weight:950}.page-title p{margin:0;color:#34426f}.top-actions{position:relative;z-index:2;display:flex;align-items:center;gap:1rem}.availability{display:inline-flex;align-items:center;gap:.65rem;min-height:44px;padding:0 1rem;border:1px solid var(--line);border-radius:18px;background:#fff;font-weight:850}.availability:before{content:"";width:10px;height:10px;border-radius:50%;background:var(--green)}.bell{position:relative;display:grid;place-items:center;width:48px;height:48px;border:0;background:transparent;color:#172447;font-size:1.55rem}.bell span{position:absolute;top:0;right:0;display:grid;place-items:center;width:24px;height:24px;border-radius:50%;color:#fff;background:var(--green);font-size:.75rem;font-weight:950}.doctor-top{display:grid;grid-template-columns:48px auto 20px;align-items:center;gap:.7rem}.doctor-top .avatar{width:48px;height:48px;font-size:1.25rem}.doctor-top strong{display:block;font-weight:950}.doctor-top span{color:#34426f;font-size:.82rem}
        .history-shell{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:.9rem;align-items:start}.history-shell>*{min-width:0}.panel{border:1px solid var(--line);border-radius:10px;background:#fff;box-shadow:var(--shadow)}.history-main{min-width:0;overflow:hidden;padding:1rem}.filters{display:grid;grid-template-columns:minmax(210px,1.25fr) minmax(110px,.62fr) minmax(120px,.68fr) minmax(135px,.78fr) minmax(190px,1fr) minmax(150px,.82fr);gap:.7rem;margin-bottom:1.1rem}.filters>*{min-width:0}.search-box,.select-box,.date-box{position:relative}.search-box input,.select-box select,.date-box input{width:100%;height:44px;min-width:0;padding:0 2.35rem 0 1rem;border:1px solid #d7e0ee;border-radius:7px;background:#fff;color:#071438;outline:none;text-overflow:ellipsis}.search-box i,.select-box i,.date-box i{position:absolute;top:50%;right:.85rem;color:#22325a;transform:translateY(-50%)}.export-btn{display:inline-flex;align-items:center;justify-content:center;gap:.55rem;height:44px;min-width:0;padding:0 .85rem;border:1px solid #8bd5a3;border-radius:7px;color:var(--green-dark);background:#fff;font-weight:950;white-space:nowrap}
        .stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-bottom:1.25rem}.stat-card{display:grid;grid-template-columns:76px minmax(0,1fr);align-items:center;gap:.9rem;min-height:112px;padding:1rem 1.2rem}.stat-icon{display:grid;place-items:center;width:62px;height:62px;border-radius:50%;color:var(--green);background:#eafaef;font-size:1.7rem}.stat-icon.orange{color:var(--orange);background:#fff0df}.stat-icon.blue{color:#176ce0;background:#eaf3ff}.stat-card h2{margin:0 .2rem .35rem 0;font-size:.9rem;font-weight:950}.stat-card strong{display:inline-block;color:var(--green-dark);font-size:1.85rem;line-height:1;font-weight:950}.stat-card small{margin-left:.45rem;color:var(--orange);font-weight:950}.stat-card p{margin:.35rem 0 0;color:#34426f;font-size:.88rem}.stat-card .good{color:var(--green)}
        .table-card{overflow:hidden;border:1px solid var(--line);border-radius:10px}.history-table{width:100%;table-layout:fixed;border-collapse:collapse}.history-table th{padding:.95rem .9rem;color:var(--green-dark);background:linear-gradient(90deg,#edf6ed,#f6fbf4);font-size:.82rem;font-weight:950;text-align:left}.history-table td{padding:1rem .9rem;border-bottom:1px solid #e9eef5;vertical-align:middle;font-size:.86rem;overflow-wrap:anywhere}.history-table th:nth-child(1){width:118px}.history-table th:nth-child(2){width:250px}.history-table th:nth-child(3){width:155px}.history-table th:nth-child(4){width:122px}.history-table th:nth-child(5){width:126px}.history-table th:nth-child(6){width:120px}.history-table th:nth-child(7){width:148px}.history-table tr.active-row{background:#f6fff8;box-shadow:inset 3px 0 0 #8bd5a3}.person{display:grid;grid-template-columns:46px minmax(0,1fr);align-items:center;gap:.75rem}.person strong{display:block;font-weight:950}.muted{color:#34426f}.type{display:inline-grid;grid-template-columns:18px auto;gap:.35rem;color:var(--green-dark);font-weight:850}.type.follow{color:var(--orange)}.triage{font-weight:950;line-height:1.45}.triage.red{color:red}.triage.orange{color:var(--orange)}.triage.green{color:var(--green-dark)}.status{display:inline-grid;place-items:center;width:max-content;padding:.25rem .55rem;border:1px solid #a9dfba;border-radius:6px;color:var(--green-dark);background:#eefaf3;font-size:.75rem;font-weight:950}.status.purple{color:#6d35df;border-color:#d6c8ff;background:#f5f0ff}.view-btn{display:inline-flex;align-items:center;justify-content:center;gap:.45rem;min-height:34px;padding:0 .8rem;border:1px solid #9eddb4;border-radius:7px;color:var(--green-dark);background:#fff;font-weight:950;white-space:nowrap}.more-btn{display:inline-grid;place-items:center;width:28px;height:34px;border:0;background:transparent;color:#27364f;font-size:1.22rem;vertical-align:middle}.table-foot{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:.75rem 1rem;color:#34426f;font-size:.82rem}.pages{display:flex;gap:.35rem}.page-btn{display:grid;place-items:center;min-width:30px;height:30px;border:1px solid #d7e0ee;border-radius:6px;background:#fff;font-weight:850}.page-btn.active{color:#fff;background:var(--green);border-color:var(--green)}.rows-select{display:inline-flex;align-items:center;gap:.5rem}.rows-select select{height:32px;border:1px solid #d7e0ee;border-radius:6px;padding:0 .65rem;background:#fff}
        .detail-panel{min-width:0;overflow:hidden}.detail-head{display:flex;align-items:center;justify-content:space-between;padding:1.1rem 1.2rem;border-bottom:1px solid var(--line)}.detail-head h2{margin:0;font-size:1.1rem;font-weight:950}.close-btn{border:0;background:transparent;color:#172447;font-size:1.4rem}.selected-profile{padding:1.25rem;text-align:center;border-bottom:1px solid var(--line)}.selected-profile .mini-avatar{width:64px;height:64px;margin:0 auto .6rem;font-size:1.6rem}.selected-profile h3{margin:0;font-size:1rem;font-weight:950}.profile-line{display:flex;justify-content:center;gap:.55rem;margin:.25rem 0 .8rem;color:#34426f;font-size:.86rem}.profile-link{display:inline-flex;align-items:center;gap:.45rem;min-height:36px;padding:0 .9rem;border:1px solid #9eddb4;border-radius:7px;color:var(--green-dark);background:#f4fff7;font-weight:950}.detail-list{display:grid;gap:1.1rem;padding:1.25rem}.detail-row{display:grid;grid-template-columns:24px minmax(88px,.72fr) minmax(0,1fr);gap:.65rem;align-items:start}.detail-row i{color:var(--green);font-size:1.05rem}.detail-row span{color:#34426f;font-weight:850}.detail-row strong{font-weight:850;overflow-wrap:anywhere}.detail-actions{display:grid;gap:.75rem;padding:0 1.25rem 1.25rem}.full-btn{display:flex;align-items:center;justify-content:center;gap:.55rem;min-height:48px;border:0;border-radius:8px;color:#fff;background:linear-gradient(90deg,#078232,#009b42);font-weight:950}.outline-green{display:flex;align-items:center;justify-content:center;gap:.55rem;min-height:44px;border:1px solid #9eddb4;border-radius:8px;color:var(--green-dark);background:#fff;font-weight:950}.info-note{display:flex;align-items:center;gap:.8rem;margin-top:.9rem;padding:.95rem 1rem;border:1px solid #cfe8d8;border-radius:8px;color:var(--green-dark);background:#f3fbf5;font-size:.9rem}.footer{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin:1rem -1.65rem 0;padding:1.05rem 1.65rem;color:var(--green-dark);background:linear-gradient(90deg,#eef8ef,#f8fcf4);font-size:.88rem}.footer-left{display:flex;gap:1rem}.footer em{font-family:"Brush Script MT","Segoe Script",cursive;font-size:1.2rem}
        .menu-toggle,.sidebar-overlay{display:none}@media(max-width:1500px){.history-shell{grid-template-columns:1fr}.detail-panel{max-width:none}.filters{grid-template-columns:repeat(3,1fr)}.stats-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:1180px){.app-shell,body.sidebar-collapsed .app-shell{grid-template-columns:1fr}.sidebar-collapse{display:none}.menu-toggle{position:fixed;top:1rem;left:1rem;z-index:1100;display:grid;place-items:center;width:48px;height:48px;border:1px solid var(--line);border-radius:12px;color:var(--green-dark);background:#fff;box-shadow:0 10px 24px rgba(24,39,75,.12);font-size:1.55rem}.sidebar-overlay{position:fixed;inset:0;z-index:1050;display:block;background:rgba(7,20,56,.42);opacity:0;pointer-events:none;transition:opacity .2s ease}body.sidebar-open .sidebar-overlay{opacity:1;pointer-events:auto}.sidebar{position:fixed;inset:0 auto 0 0;z-index:1060;width:min(84vw,310px);height:100vh;transform:translateX(-100%);transition:transform .24s ease;box-shadow:12px 0 36px rgba(7,20,56,.18)}body.sidebar-open .sidebar{transform:translateX(0)}.main{padding-top:5rem}.topbar{grid-template-columns:1fr}.topbar:after{left:20%;width:70vw}.top-actions{justify-content:flex-start}.table-card{overflow-x:auto}.history-table{min-width:920px}}@media(max-width:760px){.main{padding-inline:1rem}.top-actions{display:none}.filters,.stats-grid{grid-template-columns:1fr}.table-foot{align-items:flex-start;flex-direction:column}.footer{display:block;margin-inline:-1rem;padding-inline:1rem}.footer-left{flex-wrap:wrap;margin-bottom:.45rem}.detail-row{grid-template-columns:24px 1fr}.detail-row strong{grid-column:2}}
    </style>
</head>
<body>
    <button class="menu-toggle" type="button" aria-label="Open navigation" aria-controls="physicianSidebar" aria-expanded="false"><i class="bi bi-list"></i></button>
    <div class="app-shell">
        <aside class="sidebar" id="physicianSidebar">
            <a class="brand" href="dashboard.php"><img src="../auth/assets/img/CLSU_Logo.jpg" alt="CLSU logo"><span><strong>CLSU Infirmary</strong>Telemedicine System</span></a>
            <div class="physician-mini"><div class="avatar" aria-hidden="true"><i class="bi bi-person-fill"></i></div><div><h2>Dr. Juan Dela Cruz</h2><p>Physician</p><span class="online">Available</span></div></div>
            <button class="sidebar-collapse" type="button" aria-label="Collapse sidebar" aria-expanded="true"><i class="bi bi-layout-sidebar-inset"></i><span>Collapse</span></button>
            <nav aria-label="Physician navigation">
                <ul class="nav-list">
                    <li><a class="nav-link" href="dashboard.php"><i class="bi bi-house-door"></i> Dashboard</a></li>
                    <li><a class="nav-link" href="consultationinbox.php"><i class="bi bi-inbox"></i> Consultation Inbox <span class="nav-badge">8</span></a></li>
                    <li><a class="nav-link" href="activeconsultation.php"><i class="bi bi-clipboard2-pulse"></i> Active Consultations <span class="nav-badge">4</span></a></li>
                    <li><a class="nav-link" href="followup.php"><i class="bi bi-calendar2-check"></i> Follow-up Requests <span class="nav-badge">6</span></a></li>
                    <li><a class="nav-link" href="patientdirect.php"><i class="bi bi-people"></i> Patient Directory</a></li>
                    <li><a class="nav-link active" href="consultationhistory.php"><i class="bi bi-card-list"></i> Consultation History</a></li>
                    <li><a class="nav-link" href="notification.php"><i class="bi bi-bell"></i> Notifications <span class="nav-badge">3</span></a></li>
                </ul>
                <ul class="nav-secondary"><li><a class="nav-link" href="profile.php"><i class="bi bi-person"></i> Profile</a></li><li><a class="nav-link" href="#"><i class="bi bi-gear"></i> Settings</a></li></ul>
            </nav>
            <section class="campus-card"><div class="campus-art" aria-hidden="true"></div><h3>Central Luzon State University</h3><p>Nurturing a Culture of Excellence</p></section>
            <a class="nav-link logout-link" href="../auth/index.php"><i class="bi bi-box-arrow-left"></i> Logout</a>
        </aside>

        <main class="main">
            <header class="topbar">
                <div class="page-title"><h1>Consultation History</h1><p>View and manage all consultations you have handled.</p></div>
                <div class="top-actions"><button class="availability" type="button">Available <i class="bi bi-chevron-down"></i></button><button class="bell" type="button" aria-label="Notifications"><i class="bi bi-bell"></i><span>3</span></button><div class="doctor-top"><span class="avatar"><i class="bi bi-person-fill"></i></span><div><strong>Dr. Juan Dela Cruz</strong><span>Physician</span></div><i class="bi bi-chevron-down"></i></div></div>
            </header>

            <div class="history-shell">
                <section class="panel history-main">
                    <div class="filters">
                        <label class="search-box"><input type="search" placeholder="Search patient name, ID, or concern..."><i class="bi bi-search"></i></label>
                        <label class="select-box"><select><option>All Types</option></select><i class="bi bi-chevron-down"></i></label>
                        <label class="select-box"><select><option>All Statuses</option></select><i class="bi bi-chevron-down"></i></label>
                        <label class="select-box"><select><option>All Triage Levels</option></select><i class="bi bi-chevron-down"></i></label>
                        <label class="date-box"><input value="May 10, 2025 - May 16, 2025"><i class="bi bi-calendar3"></i></label>
                        <button class="export-btn" type="button"><i class="bi bi-download"></i>Export Summary</button>
                    </div>

                    <section class="stats-grid" aria-label="Consultation history summary">
                        <article class="panel stat-card"><span class="stat-icon"><i class="bi bi-file-earmark-medical-fill"></i></span><div><h2>Total Consultations</h2><strong>128</strong><p>Handled</p></div></article>
                        <article class="panel stat-card"><span class="stat-icon"><i class="bi bi-check-circle"></i></span><div><h2>Completed</h2><strong>96</strong><p class="good">75%</p></div></article>
                        <article class="panel stat-card"><span class="stat-icon orange"><i class="bi bi-arrow-up"></i></span><div><h2>Escalated</h2><strong>18</strong><small>14%</small></div></article>
                        <article class="panel stat-card"><span class="stat-icon blue"><i class="bi bi-people"></i></span><div><h2>Follow-up</h2><strong>27</strong><small class="good">21%</small></div></article>
                    </section>

                    <div class="table-card">
                        <table class="history-table" aria-label="Consultation history">
                            <thead><tr><th>Date &amp; Time</th><th>Patient</th><th>Type</th><th>Triage Level</th><th>Status</th><th>Outcome</th><th>Actions</th></tr></thead>
                            <tbody>
                                <tr class="active-row"><td>May 16, 2025<br><span class="muted">10:20 AM</span></td><td><div class="person"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Maria Dela Cruz</strong><span class="muted">ID: 2025-00123</span></div></div></td><td><span class="type"><i class="bi bi-chat-dots"></i>Chat<br>Consultation</span></td><td class="triage orange">Level 2<br>Urgent</td><td><span class="status">Completed</span><br><span class="muted">10:45 AM</span></td><td>Advice Given</td><td><a class="view-btn" href="#"><i class="bi bi-eye"></i>View</a> <button class="more-btn" type="button"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                                <tr><td>May 16, 2025<br><span class="muted">09:45 AM</span></td><td><div class="person"><span class="mini-avatar male"><i class="bi bi-person-fill"></i></span><div><strong>Juan Miguel Santos</strong><span class="muted">ID: 2025-00118</span></div></div></td><td><span class="type"><i class="bi bi-chat-dots"></i>Chat<br>Consultation</span></td><td class="triage orange">Level 3<br>Moderate</td><td><span class="status">Completed</span><br><span class="muted">10:05 AM</span></td><td>Advice Given</td><td><a class="view-btn" href="#"><i class="bi bi-eye"></i>View</a> <button class="more-btn" type="button"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                                <tr><td>May 15, 2025<br><span class="muted">04:15 PM</span></td><td><div class="person"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Angela Reyes</strong><span class="muted">ID: 2025-00120</span></div></div></td><td><span class="type follow"><i class="bi bi-person-plus"></i>Follow-up<br>Request</span></td><td class="triage red">Level 2<br>Urgent</td><td><span class="status">Completed</span><br><span class="muted">04:35 PM</span></td><td>Symptoms<br>Improved</td><td><a class="view-btn" href="#"><i class="bi bi-eye"></i>View</a> <button class="more-btn" type="button"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                                <tr><td>May 15, 2025<br><span class="muted">02:30 PM</span></td><td><div class="person"><span class="mini-avatar male"><i class="bi bi-person-fill"></i></span><div><strong>Pedro Garcia</strong><span class="muted">ID: 2025-00115</span></div></div></td><td><span class="type"><i class="bi bi-chat-dots"></i>Chat<br>Consultation</span></td><td class="triage red">Level 1<br>Emergency</td><td><span class="status purple">Escalated</span><br><span class="muted">02:40 PM</span></td><td>Escalated to<br>Physician</td><td><a class="view-btn" href="#"><i class="bi bi-eye"></i>View</a> <button class="more-btn" type="button"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                                <tr><td>May 15, 2025<br><span class="muted">11:05 AM</span></td><td><div class="person"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Katrina Lopez</strong><span class="muted">ID: 2025-00121</span></div></div></td><td><span class="type"><i class="bi bi-chat-dots"></i>Chat<br>Consultation</span></td><td class="triage green">Level 4<br>Non-urgent</td><td><span class="status">Completed</span><br><span class="muted">11:25 AM</span></td><td>Advice Given</td><td><a class="view-btn" href="#"><i class="bi bi-eye"></i>View</a> <button class="more-btn" type="button"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                                <tr><td>May 14, 2025<br><span class="muted">03:10 PM</span></td><td><div class="person"><span class="mini-avatar male"><i class="bi bi-person-fill"></i></span><div><strong>Kevin Lopez</strong><span class="muted">ID: 2025-00125</span></div></div></td><td><span class="type"><i class="bi bi-chat-dots"></i>Chat<br>Consultation</span></td><td class="triage red">Level 2<br>Urgent</td><td><span class="status">Completed</span><br><span class="muted">03:30 PM</span></td><td>Referred to<br>Clinic</td><td><a class="view-btn" href="#"><i class="bi bi-eye"></i>View</a> <button class="more-btn" type="button"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                                <tr><td>May 14, 2025<br><span class="muted">10:25 AM</span></td><td><div class="person"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Rhea Mae Villanueva</strong><span class="muted">ID: 2025-00130</span></div></div></td><td><span class="type"><i class="bi bi-chat-dots"></i>Chat<br>Consultation</span></td><td class="triage orange">Level 3<br>Moderate</td><td><span class="status">Completed</span><br><span class="muted">10:50 AM</span></td><td>Advice Given</td><td><a class="view-btn" href="#"><i class="bi bi-eye"></i>View</a> <button class="more-btn" type="button"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                                <tr><td>May 13, 2025<br><span class="muted">09:00 AM</span></td><td><div class="person"><span class="mini-avatar male"><i class="bi bi-person-fill"></i></span><div><strong>John Paul Dela Cruz</strong><span class="muted">ID: 2025-00110</span></div></div></td><td><span class="type follow"><i class="bi bi-person-plus"></i>Follow-up<br>Request</span></td><td class="triage red">Level 2<br>Urgent</td><td><span class="status">Completed</span><br><span class="muted">09:15 AM</span></td><td>For<br>Monitoring</td><td><a class="view-btn" href="#"><i class="bi bi-eye"></i>View</a> <button class="more-btn" type="button"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                            </tbody>
                        </table>
                        <div class="table-foot"><span>Showing 1 to 8 of 128 consultations</span><div class="pages"><button class="page-btn" type="button"><i class="bi bi-chevron-left"></i></button><button class="page-btn active" type="button">1</button><button class="page-btn" type="button">2</button><button class="page-btn" type="button">3</button><button class="page-btn" type="button">4</button><button class="page-btn" type="button">5</button><button class="page-btn" type="button">...</button><button class="page-btn" type="button">16</button><button class="page-btn" type="button"><i class="bi bi-chevron-right"></i></button></div><label class="rows-select">Rows per page:<select><option>8</option></select></label></div>
                    </div>
                    <div class="info-note"><i class="bi bi-info-circle-fill"></i><span>This history includes consultations you have handled. Click "View" to see full details, notes, and communications.</span></div>
                </section>

                <aside class="panel detail-panel">
                    <header class="detail-head"><h2>Consultation Detail</h2><button class="close-btn" type="button" aria-label="Close"><i class="bi bi-x-lg"></i></button></header>
                    <section class="selected-profile"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><h3>Maria Dela Cruz <span class="status ms-2">Completed</span></h3><p class="muted mb-0">ID: 2025-00123</p><div class="profile-line"><span>20 yrs</span><span>&bull;</span><span>Female</span><span>&bull;</span><span>Student</span></div><a class="profile-link" href="patientdirect.php"><i class="bi bi-person-vcard"></i>View Patient Profile</a></section>
                    <div class="detail-list">
                        <div class="detail-row"><i class="bi bi-calendar3"></i><span>Date &amp; Time</span><strong>May 16, 2025 &bull; 10:20 AM</strong></div>
                        <div class="detail-row"><i class="bi bi-chat-dots"></i><span>Type</span><strong>Chat Consultation</strong></div>
                        <div class="detail-row"><i class="bi bi-arrow-up"></i><span>Triage Level</span><strong class="triage red">Level 2 - Urgent</strong></div>
                        <div class="detail-row"><i class="bi bi-check2-circle"></i><span>Status</span><strong><span class="status">Completed</span><br>10:45 AM</strong></div>
                        <div class="detail-row"><i class="bi bi-person"></i><span>Handled By</span><strong>Dr. Juan Dela Cruz</strong></div>
                        <div class="detail-row"><i class="bi bi-clipboard2-pulse"></i><span>Chief Complaint</span><strong>Fever and cough for 2 days</strong></div>
                        <div class="detail-row"><i class="bi bi-check-square"></i><span>Outcome</span><strong>Advice Given</strong></div>
                        <div class="detail-row"><i class="bi bi-card-text"></i><span>Notes Summary</span><strong>Advised rest, increased fluids, and Paracetamol 500mg q8h as needed. Patient was advised to seek medical attention if symptoms persist.</strong></div>
                        <div class="detail-row"><i class="bi bi-clock"></i><span>Duration</span><strong>25 minutes</strong></div>
                    </div>
                    <div class="detail-actions"><a class="full-btn" href="#"><i class="bi bi-eye"></i>View Full Consultation</a><button class="outline-green" type="button"><i class="bi bi-download"></i>Export This Record</button></div>
                </aside>
            </div>
            <footer class="footer"><span class="footer-left"><span>CLSU Infirmary Telemedicine System</span><span>|</span><span>Central Luzon State University</span></span><em>Nurturing a Culture of Excellence</em></footer>
        </main>
    </div>
    <div class="sidebar-overlay" data-close-sidebar></div>
    <script>
        const menuToggle=document.querySelector(".menu-toggle");
        const sidebarCollapse=document.querySelector(".sidebar-collapse");
        const sidebarOverlay=document.querySelector(".sidebar-overlay");
        const sidebarLinks=document.querySelectorAll(".sidebar .nav-link,.sidebar .brand");
        const setSidebar=(isOpen)=>{document.body.classList.toggle("sidebar-open",isOpen);menuToggle.setAttribute("aria-expanded",String(isOpen));menuToggle.setAttribute("aria-label",isOpen?"Close navigation":"Open navigation")};
        menuToggle.addEventListener("click",()=>setSidebar(!document.body.classList.contains("sidebar-open")));
        const setSidebarCollapsed=(isCollapsed)=>{document.body.classList.toggle("sidebar-collapsed",isCollapsed);sidebarCollapse.setAttribute("aria-expanded",String(!isCollapsed));sidebarCollapse.setAttribute("aria-label",isCollapsed?"Expand sidebar":"Collapse sidebar");sidebarCollapse.querySelector("span").textContent=isCollapsed?"Expand":"Collapse"};
        sidebarCollapse.addEventListener("click",()=>setSidebarCollapsed(!document.body.classList.contains("sidebar-collapsed")));
        sidebarOverlay.addEventListener("click",()=>setSidebar(false));
        sidebarLinks.forEach((link)=>link.addEventListener("click",()=>setSidebar(false)));
        document.addEventListener("keydown",(event)=>{if(event.key==="Escape")setSidebar(false)});
    </script>
</body>
</html>
