<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Consultation Inbox | CLSU Infirmary Telemedicine System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root{--ink:#12192d;--muted:#526078;--green:#087d32;--green-dark:#006824;--green-soft:#e9f5e9;--gold:#e3aa00;--gold-soft:#fff4d8;--orange:#f28a00;--orange-soft:#fff2df;--purple:#7c3df0;--purple-soft:#f0e8ff;--blue:#1266d6;--blue-soft:#eaf3ff;--red:#f52222;--red-soft:#fff0ef;--line:#e1e7ef;--shadow:0 16px 42px rgba(21,40,64,.08)}
        *{box-sizing:border-box}body{min-height:100vh;margin:0;color:var(--ink);font-family:"Inter","Segoe UI",system-ui,-apple-system,BlinkMacSystemFont,sans-serif;background:radial-gradient(circle at 88% 92%,rgba(255,211,67,.32),transparent 16rem),linear-gradient(180deg,#fbfdfb 0%,#f7faf5 100%)}a{color:inherit;text-decoration:none}button,input,select{font:inherit}
        .app-shell{display:grid;grid-template-columns:300px minmax(0,1fr);min-height:100vh;transition:grid-template-columns .2s ease}.sidebar{position:sticky;top:0;height:100vh;padding:1.55rem 1.25rem;border-right:1px solid var(--line);background:#fff;box-shadow:8px 0 28px rgba(24,39,75,.04);overflow-y:auto;transition:padding .2s ease}.brand{display:flex;align-items:center;gap:.85rem;margin-bottom:2.35rem}.brand img{width:62px;height:62px;border-radius:50%;object-fit:cover}.brand strong{display:block;color:#111;font-size:1.42rem;font-weight:950;line-height:1.05}.brand span{display:block;color:#111;font-size:1.05rem;font-weight:800}
        .avatar,.mini-avatar{display:grid;place-items:center;border-radius:50%;color:#fff;background:linear-gradient(135deg,#d29a82 0%,#4a4865 100%);overflow:hidden}.avatar{width:64px;height:64px;border:1px solid #d4dbe7;font-size:1.85rem}.mini-avatar{width:46px;height:46px;font-size:1.25rem}.physician-mini{display:grid;grid-template-columns:64px minmax(0,1fr);align-items:center;gap:.9rem;margin-bottom:1.6rem}.physician-mini h2{margin:0 0 .18rem;font-size:1rem;font-weight:950}.physician-mini p{margin:0 0 .25rem;color:var(--muted);font-size:.9rem}.online{display:inline-flex;align-items:center;gap:.38rem;color:#2d405f;font-size:.82rem}.online:before{content:"";width:10px;height:10px;border-radius:50%;background:var(--green)}
        .sidebar-collapse{display:flex;align-items:center;justify-content:center;gap:.55rem;width:100%;min-height:42px;margin:0 0 1rem;border:1px solid #d7e0ee;border-radius:9px;color:var(--green-dark);background:#fff;font-weight:950}.nav-list{display:grid;gap:.45rem;margin:0;padding:0 0 1.4rem;border-bottom:1px solid var(--line);list-style:none}.nav-secondary{display:grid;gap:.45rem;margin:1.25rem 0 1.6rem;padding:0;list-style:none}.nav-link{position:relative;display:flex;align-items:center;gap:1rem;min-height:56px;padding:.8rem .95rem;border-radius:10px;color:#1d293f;font-weight:850}.nav-link:before{content:"";position:absolute;left:-1.25rem;width:8px;height:44px;border-radius:0 8px 8px 0;background:transparent}.nav-link i{width:28px;color:#5d697d;font-size:1.35rem}.nav-link.active{color:var(--green-dark);background:linear-gradient(90deg,#e7f4e6,#f5faf3)}.nav-link.active:before{background:var(--green)}.nav-link.active i{color:var(--green)}.nav-badge{display:grid;place-items:center;min-width:24px;height:24px;margin-left:auto;padding:0 .4rem;border-radius:999px;color:#fff;background:var(--green);font-size:.76rem;font-weight:950}.logout-link{margin-top:1.2rem}
        body.sidebar-collapsed .app-shell{grid-template-columns:88px minmax(0,1fr)}body.sidebar-collapsed .sidebar{padding-inline:.75rem;overflow-x:hidden}body.sidebar-collapsed .brand{justify-content:center;gap:0;margin-bottom:1.5rem}body.sidebar-collapsed .brand span,body.sidebar-collapsed .physician-mini > div:last-child,body.sidebar-collapsed .sidebar-collapse span{display:none}body.sidebar-collapsed .brand img,body.sidebar-collapsed .avatar{width:48px;height:48px}body.sidebar-collapsed .physician-mini{grid-template-columns:1fr;justify-items:center;margin-bottom:1rem}body.sidebar-collapsed .sidebar-collapse{width:48px;margin-inline:auto}body.sidebar-collapsed .nav-link{justify-content:center;gap:0;padding-inline:.6rem;font-size:0}body.sidebar-collapsed .nav-link i{width:auto;font-size:1.45rem}body.sidebar-collapsed .nav-badge{position:absolute;top:5px;right:4px;min-width:18px;height:18px;margin-left:0;padding:0 .25rem;font-size:.62rem}body.sidebar-collapsed .logout-link{margin-top:2rem}
        .main{min-width:0;padding:1.65rem 1.9rem 1.2rem}.topbar{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:1.25rem;align-items:start;margin-bottom:1.2rem;overflow:hidden}.topbar:after{content:"";position:absolute;left:39%;top:-1.2rem;width:min(500px,34vw);height:120px;opacity:.18;background:linear-gradient(180deg,transparent 52%,#2c7141 0);clip-path:polygon(0 72%,13% 58%,20% 61%,25% 33%,31% 61%,47% 41%,58% 64%,72% 43%,84% 60%,100% 68%,100% 100%,0 100%);pointer-events:none}.page-title{position:relative;z-index:1}.page-title h1{margin:0 0 .55rem;font-size:clamp(1.8rem,2.55vw,2.45rem);font-weight:950}.page-title p{margin:0;color:#34426f}.top-actions{position:relative;z-index:2;display:flex;align-items:center;gap:1.15rem}.bell{position:relative;display:grid;place-items:center;width:48px;height:48px;border:0;background:transparent;color:#172447;font-size:1.65rem}.bell span{position:absolute;top:2px;right:0;display:grid;place-items:center;min-width:23px;height:23px;padding:0 .35rem;border-radius:999px;color:#fff;background:var(--green);font-size:.74rem;font-weight:950}.datebox{color:#34426f;font-weight:800}.datebox strong{display:block;color:#111735}.doctor-avatar{display:grid;place-items:center;width:72px;height:72px;border-radius:50%;border:1px solid var(--line);background:linear-gradient(145deg,#ffd0b5,#243452);color:#fff;font-size:2rem;box-shadow:0 10px 24px rgba(30,57,48,.08)}
        .stats-grid{display:grid;grid-template-columns:repeat(4,minmax(180px,1fr));gap:1rem;margin-bottom:1rem}.cardx{border:1px solid var(--line);border-radius:12px;background:rgba(255,255,255,.92);box-shadow:var(--shadow)}.stat-card{display:grid;grid-template-columns:72px minmax(0,1fr);gap:1rem;align-items:center;min-height:118px;padding:1.2rem}.stat-icon{display:grid;place-items:center;width:62px;height:62px;border-radius:13px;color:var(--green);background:var(--green-soft);font-size:1.85rem}.stat-icon.orange{color:var(--orange);background:var(--orange-soft)}.stat-icon.purple{color:var(--purple);background:var(--purple-soft)}.stat-card strong{display:block;font-size:2rem;line-height:1;font-weight:950}.stat-card h2{margin:.25rem 0 .25rem;font-size:.98rem;font-weight:950}.stat-card p{margin:0;color:#3f4c64;font-size:.88rem}
        .inbox-panel{overflow:hidden}.toolbar{display:grid;grid-template-columns:auto minmax(280px,1fr) auto;gap:.85rem;align-items:center;padding:1rem 1.1rem}.select-btn,.filter-btn,.search-box input{height:44px;border:1px solid #d7e0ee;border-radius:8px;background:#fff;color:#071438}.select-btn,.filter-btn{display:inline-flex;align-items:center;justify-content:center;gap:.6rem;padding:0 1rem;font-weight:950}.search-box{position:relative}.search-box input{width:100%;padding:0 1rem 0 3rem}.search-box i{position:absolute;left:1rem;top:50%;transform:translateY(-50%);color:#536179;font-size:1.15rem}
        .table-wrap{overflow-x:auto;padding:0 1.1rem}.inbox-table{width:100%;min-width:980px;border-collapse:collapse}.inbox-table th,.inbox-table td{padding:1rem;border-bottom:1px solid #edf1f7;text-align:left;vertical-align:middle;font-size:.9rem}.inbox-table th{color:var(--green-dark);background:linear-gradient(90deg,#eef8ee,#f6fbf5);font-weight:950}.patient-cell{display:grid;grid-template-columns:58px minmax(0,1fr);gap:.8rem;align-items:center}.patient-cell strong,.complaint strong{display:block;font-weight:950}.patient-cell span,.complaint span,.assigned{color:#34426f}.patient-meta{display:block;margin-top:.25rem}.triage,.status{display:inline-grid;gap:.25rem;place-items:center;min-width:94px;padding:.45rem .65rem;border-radius:8px;font-weight:950;font-size:.84rem}.triage small{font-weight:950}.triage.l1{color:var(--red);background:var(--red-soft);border:1px solid #ffd0cd}.triage.l2,.status.pending{color:#db7600;background:#fff7e8;border:1px solid #f8dba8}.triage.l3{color:#d99a00;background:#fff8e1;border:1px solid #f6dfa1}.triage.l4{color:var(--blue);background:var(--blue-soft);border:1px solid #cfe0ff}.triage small:before{content:"";display:inline-block;width:9px;height:9px;margin-right:.35rem;border-radius:50%;background:currentColor}.status.progress{display:inline-flex;align-items:center;justify-content:center;gap:.4rem;width:116px;min-width:116px;min-height:38px;white-space:nowrap;color:var(--blue);background:var(--blue-soft);border:1px solid #cfe0ff}.action-btn{display:inline-flex;align-items:center;justify-content:center;min-width:128px;height:38px;border:1px solid #49a16b;border-radius:7px;color:var(--green-dark);background:#fff;font-weight:950}.more-btn{display:inline-grid;place-items:center;width:34px;height:34px;border:0;background:transparent;color:#1d293f;font-size:1.25rem}.pager{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem 1.35rem;color:#34426f;font-size:.9rem}.pages{display:flex;gap:.55rem}.page-btn{display:grid;place-items:center;min-width:38px;height:38px;border:1px solid #d7e0ee;border-radius:7px;background:#fff;color:#071438;font-weight:950}.page-btn.active{color:#fff;background:var(--green);border-color:var(--green)}
        .footer{display:flex;align-items:center;gap:1.35rem;margin-top:1.55rem;color:var(--green-dark);font-size:.9rem}.footer em{margin-left:auto;font-family:"Brush Script MT","Segoe Script",cursive;font-size:1.2rem}.menu-toggle,.sidebar-overlay{display:none}
        @media(max-width:1320px){.stats-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:980px){.app-shell,body.sidebar-collapsed .app-shell{grid-template-columns:1fr}.sidebar-collapse{display:none}.menu-toggle{position:fixed;top:1rem;left:1rem;z-index:1100;display:grid;place-items:center;width:48px;height:48px;border:1px solid var(--line);border-radius:12px;color:var(--green-dark);background:#fff;box-shadow:0 10px 24px rgba(24,39,75,.12);font-size:1.55rem}.sidebar-overlay{position:fixed;inset:0;z-index:1050;display:block;background:rgba(7,20,56,.42);opacity:0;pointer-events:none;transition:opacity .2s ease}body.sidebar-open .sidebar-overlay{opacity:1;pointer-events:auto}.sidebar{position:fixed;inset:0 auto 0 0;z-index:1060;width:min(84vw,310px);height:100vh;transform:translateX(-100%);transition:transform .24s ease;box-shadow:12px 0 36px rgba(7,20,56,.18)}body.sidebar-open .sidebar{transform:translateX(0)}.main{padding-top:5rem}.topbar{grid-template-columns:1fr}.topbar:after{left:20%;width:70vw}.top-actions{justify-content:flex-start}.toolbar{grid-template-columns:1fr}.footer{display:block}.footer em{display:block;margin-top:.5rem}}@media(max-width:640px){.main{padding-inline:1rem}.stats-grid{grid-template-columns:1fr}.stat-card{grid-template-columns:64px 1fr}.stat-icon{width:58px;height:58px}.datebox{display:none}.doctor-avatar{width:56px;height:56px}.pager{align-items:flex-start;flex-direction:column}}
    </style>
</head>
<body>
    <button class="menu-toggle" type="button" aria-label="Open navigation" aria-controls="physicianSidebar" aria-expanded="false"><i class="bi bi-list"></i></button>
    <div class="app-shell">
        <aside class="sidebar" id="physicianSidebar">
            <a class="brand" href="dashboard.php"><img src="../auth/assets/img/CLSU_Logo.jpg" alt="CLSU logo"><span><strong>CLSU Infirmary</strong>Telemedicine System</span></a>
            <div class="physician-mini"><div class="avatar" aria-hidden="true"><i class="bi bi-person-fill"></i></div><div><h2>Dr. Juan Dela Cruz</h2><p>Physician</p><span class="online">Online</span></div></div>
            <button class="sidebar-collapse" type="button" aria-label="Collapse sidebar" aria-expanded="true"><i class="bi bi-layout-sidebar-inset"></i><span>Collapse</span></button>
            <nav aria-label="Physician navigation">
                <ul class="nav-list">
                    <li><a class="nav-link" href="dashboard.php"><i class="bi bi-house-door"></i> Dashboard</a></li>
                    <li><a class="nav-link active" href="consultationinbox.php"><i class="bi bi-inbox"></i> Consultation Inbox <span class="nav-badge">8</span></a></li>
                    <li><a class="nav-link" href="activeconsultation.php"><i class="bi bi-clipboard2-pulse"></i> Active Consultations <span class="nav-badge">4</span></a></li>
                    <li><a class="nav-link" href="followup.php"><i class="bi bi-calendar2-check"></i> Follow-up Requests <span class="nav-badge">6</span></a></li>
                    <li><a class="nav-link" href="patientdirect.php"><i class="bi bi-people"></i> Patient Directory</a></li>
                    <li><a class="nav-link" href="consultationhistory.php"><i class="bi bi-card-list"></i> Consultation History</a></li>
                    <li><a class="nav-link" href="notification.php"><i class="bi bi-bell"></i> Notifications <span class="nav-badge">3</span></a></li>
                </ul>
                <ul class="nav-secondary">
                    <li><a class="nav-link" href="profile.php"><i class="bi bi-person"></i> Profile</a></li>
                    <li><a class="nav-link" href="#"><i class="bi bi-gear"></i> Settings</a></li>
                </ul>
            </nav>
            <a class="nav-link logout-link" href="../auth/index.php"><i class="bi bi-box-arrow-right"></i> Log out</a>
        </aside>

        <main class="main">
            <header class="topbar">
                <div class="page-title">
                    <h1>Consultation Inbox</h1>
                    <p>Review the consultations assigned to you for online consultation.</p>
                </div>
                <div class="top-actions">
                    <button class="bell" type="button" aria-label="Notifications"><i class="bi bi-bell"></i><span>4</span></button>
                    <div class="datebox"><strong>May 16, 2025</strong>Friday, 10:36 AM</div>
                    <span class="doctor-avatar" aria-label="Dr. Juan Dela Cruz"><i class="bi bi-person-fill"></i></span>
                </div>
            </header>

            <section class="stats-grid" aria-label="Inbox summary">
                <article class="cardx stat-card"><span class="stat-icon"><i class="bi bi-inbox-fill"></i></span><div><strong>12</strong><h2>Pending</h2><p>Awaiting action</p></div></article>
                <article class="cardx stat-card"><span class="stat-icon orange"><i class="bi bi-chat-dots-fill"></i></span><div><strong>3</strong><h2>In Progress</h2><p>Current consultations</p></div></article>
                <article class="cardx stat-card"><span class="stat-icon purple"><i class="bi bi-people-fill"></i></span><div><strong>5</strong><h2>Follow-up Requested</h2><p>May follow-up request</p></div></article>
                <article class="cardx stat-card"><span class="stat-icon"><i class="bi bi-check-circle-fill"></i></span><div><strong>42</strong><h2>Completed <span class="fw-normal">(This Month)</span></h2><p>Completed this month</p></div></article>
            </section>

            <section class="cardx inbox-panel">
                <div class="toolbar">
                    <button class="select-btn" type="button">All Status <i class="bi bi-chevron-down"></i></button>
                    <label class="search-box"><i class="bi bi-search"></i><input type="search" placeholder="Search patient, symptom, or ID..."></label>
                    <button class="filter-btn" type="button"><i class="bi bi-funnel"></i> Filters</button>
                </div>
                <div class="table-wrap">
                    <table class="inbox-table">
                        <thead><tr><th>Patient</th><th>Chief Complaint / Summary</th><th>Triage Level</th><th>Status</th><th>Assigned</th><th>Actions</th><th></th></tr></thead>
                        <tbody>
                            <tr><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Maria Dela Cruz</strong><span class="patient-meta">ID: 2025-0516-001<br>22 yrs &bull; Female</span></div></div></td><td class="complaint"><strong>Headache, cough, and colds</strong><span>Fever started yesterday with body aches.</span></td><td><span class="triage l1">Level 1<small>Emergency</small></span></td><td><span class="status pending">Pending</span></td><td class="assigned">May 16, 2025<br>10:20 AM</td><td><a class="action-btn" href="activeconsultation.php">Start Consultation</a></td><td><button class="more-btn" type="button" aria-label="More actions"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                            <tr><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>John Miguel Santos</strong><span class="patient-meta">ID: 2025-0516-002<br>24 yrs &bull; Male</span></div></div></td><td class="complaint"><strong>Fever and body pain</strong><span>Fever and weakness started last night.</span></td><td><span class="triage l2">Level 2<small>Urgent</small></span></td><td><span class="status pending">Pending</span></td><td class="assigned">May 16, 2025<br>10:15 AM</td><td><a class="action-btn" href="activeconsultation.php">Start Consultation</a></td><td><button class="more-btn" type="button" aria-label="More actions"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                            <tr><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Mark Joseph Lim</strong><span class="patient-meta">ID: 2025-0516-004<br>23 yrs &bull; Male</span></div></div></td><td class="complaint"><strong>Stomach pain and vomiting</strong><span>Vomiting with abdominal pain since this morning.</span></td><td><span class="triage l4">Level 4<small>Non-urgent</small></span></td><td><span class="status progress"><i class="bi bi-chat-dots-fill"></i> Ongoing</span></td><td class="assigned">May 16, 2025<br>09:58 AM</td><td><a class="action-btn" href="activeconsultation.php">Continue</a></td><td><button class="more-btn" type="button" aria-label="More actions"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                            <tr><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Ella Mae Garcia</strong><span class="patient-meta">ID: 2025-0516-005<br>20 yrs &bull; Female</span></div></div></td><td class="complaint"><strong>Allergy and itchy skin</strong><span>Rashes and itching on the arms and neck.</span></td><td><span class="triage l4">Level 4<small>Non-urgent</small></span></td><td><span class="status pending">Pending</span></td><td class="assigned">May 16, 2025<br>09:45 AM</td><td><a class="action-btn" href="activeconsultation.php">Start Consultation</a></td><td><button class="more-btn" type="button" aria-label="More actions"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                            <tr><td><div class="patient-cell"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Luis Mendoza</strong><span class="patient-meta">ID: 2025-0516-006<br>25 yrs &bull; Male</span></div></div></td><td class="complaint"><strong>Cough and sore throat</strong><span>Cough and sore throat for 2 days.</span></td><td><span class="triage l3">Level 3<small>Moderate</small></span></td><td><span class="status pending">Pending</span></td><td class="assigned">May 16, 2025<br>09:30 AM</td><td><a class="action-btn" href="activeconsultation.php">Start Consultation</a></td><td><button class="more-btn" type="button" aria-label="More actions"><i class="bi bi-three-dots-vertical"></i></button></td></tr>
                        </tbody>
                    </table>
                </div>
                <div class="pager"><span>Showing 1 to 5 of 11 results</span><div class="pages"><button class="page-btn" type="button"><i class="bi bi-chevron-left"></i></button><button class="page-btn active" type="button">1</button><button class="page-btn" type="button">2</button><button class="page-btn" type="button"><i class="bi bi-chevron-right"></i></button></div></div>
            </section>

            <footer class="footer"><span>CLSU Infirmary Telemedicine System</span><span>|</span><span>Central Luzon State University</span><em>Nurturing a Culture of Excellence</em></footer>
        </main>
    </div>
    <div class="sidebar-overlay" data-close-sidebar></div>
    <script>
        const menuToggle=document.querySelector(".menu-toggle");
        const sidebarCollapse=document.querySelector(".sidebar-collapse");
        const sidebarOverlay=document.querySelector(".sidebar-overlay");
        const sidebarLinks=document.querySelectorAll(".sidebar .nav-link,.sidebar .brand");
        const setSidebar=(isOpen)=>{document.body.classList.toggle("sidebar-open",isOpen);menuToggle.setAttribute("aria-expanded",String(isOpen));menuToggle.setAttribute("aria-label",isOpen?"Close navigation":"Open navigation")};
        menuToggle.addEventListener("click",()=>setSidebar(!document.body.classList.contains("sidebar-open")));
        const setSidebarCollapsed=(isCollapsed)=>{document.body.classList.toggle("sidebar-collapsed",isCollapsed);sidebarCollapse.setAttribute("aria-expanded",String(!isCollapsed));sidebarCollapse.setAttribute("aria-label",isCollapsed?"Expand sidebar":"Collapse sidebar");sidebarCollapse.querySelector("span").textContent=isCollapsed?"Expand":"Collapse"};
        sidebarCollapse.addEventListener("click",()=>setSidebarCollapsed(!document.body.classList.contains("sidebar-collapsed")));
        sidebarOverlay.addEventListener("click",()=>setSidebar(false));
        sidebarLinks.forEach((link)=>link.addEventListener("click",()=>setSidebar(false)));
        document.addEventListener("keydown",(event)=>{if(event.key==="Escape")setSidebar(false)});
    </script>
</body>
</html>
