<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Follow-up Requests | CLSU Infirmary Telemedicine System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root{--ink:#071438;--muted:#4e5b86;--green:#087d32;--green-dark:#006824;--line:#dfe6f2;--page:#f6f9fd;--blue:#1266d6;--orange:#f27900;--purple:#7c3df0;--red:#f52222;--shadow:0 12px 30px rgba(24,39,75,.07)}
        *{box-sizing:border-box}body{min-height:100vh;margin:0;color:var(--ink);font-family:"Inter","Segoe UI",system-ui,-apple-system,BlinkMacSystemFont,sans-serif;background:var(--page)}a{color:inherit;text-decoration:none}button,input,textarea{font:inherit}
        .app-shell{display:grid;grid-template-columns:300px minmax(0,1fr);min-height:100vh;transition:grid-template-columns .2s ease}.sidebar{position:sticky;top:0;height:100vh;padding:1.55rem 1.25rem;border-right:1px solid var(--line);background:#fff;box-shadow:8px 0 28px rgba(24,39,75,.04);overflow-y:auto;transition:padding .2s ease}.brand{display:flex;align-items:center;gap:.85rem;margin-bottom:2.35rem}.brand img{width:62px;height:62px;border-radius:50%;object-fit:cover}.brand strong{display:block;color:var(--green-dark);font-size:1.35rem;font-weight:950;line-height:1.05}.brand span{display:block;color:var(--green-dark);font-size:1rem;font-weight:800}
        .avatar,.mini-avatar{display:grid;place-items:center;border-radius:50%;color:#fff;background:linear-gradient(135deg,#d29a82 0%,#4a4865 100%);overflow:hidden}.avatar{width:64px;height:64px;border:1px solid #d4dbe7;font-size:1.85rem}.mini-avatar{width:56px;height:56px;font-size:1.3rem}.physician-mini{display:grid;grid-template-columns:64px minmax(0,1fr);align-items:center;gap:.9rem;margin-bottom:1.6rem}.physician-mini h2{margin:0 0 .18rem;font-size:1rem;font-weight:950}.physician-mini p{margin:0 0 .25rem;color:var(--muted);font-size:.9rem}.online{display:inline-flex;align-items:center;gap:.38rem;color:#2d405f;font-size:.82rem}.online:before{content:"";width:10px;height:10px;border-radius:50%;background:var(--green)}
        .sidebar-collapse{display:flex;align-items:center;justify-content:center;gap:.55rem;width:100%;min-height:42px;margin:0 0 1rem;border:1px solid #d7e0ee;border-radius:9px;color:var(--green-dark);background:#fff;font-weight:950}.nav-list{display:grid;gap:.45rem;margin:0;padding:0 0 1.4rem;border-bottom:1px solid var(--line);list-style:none}.nav-secondary{display:grid;gap:.45rem;margin:1.25rem 0 1.5rem;padding:0;border-bottom:1px solid var(--line);list-style:none}.nav-link{position:relative;display:flex;align-items:center;gap:1rem;min-height:56px;padding:.8rem .95rem;border-radius:10px;color:#1d293f;font-weight:850}.nav-link:before{content:"";position:absolute;left:-1.25rem;width:8px;height:44px;border-radius:0 8px 8px 0;background:transparent}.nav-link i{width:28px;color:#5d697d;font-size:1.35rem}.nav-link.active{color:var(--green-dark);background:linear-gradient(90deg,#e7f4e6,#f5faf3)}.nav-link.active:before{background:var(--green)}.nav-link.active i{color:var(--green)}.nav-badge{display:grid;place-items:center;min-width:24px;height:24px;margin-left:auto;padding:0 .4rem;border-radius:999px;color:#fff;background:var(--green);font-size:.76rem;font-weight:950}.duty-card{margin:1.4rem 0 1.2rem;padding:1rem;border:1px solid #dcebdd;border-radius:10px;background:linear-gradient(145deg,#eef8ef,#f8fcf8);color:var(--green-dark)}.duty-card header{display:flex;align-items:center;justify-content:space-between;margin-bottom:.75rem;font-weight:950}.duty-card p{margin:.3rem 0;color:#071438;font-size:.9rem}.logout-link{margin-top:1rem}
        body.sidebar-collapsed .app-shell{grid-template-columns:88px minmax(0,1fr)}body.sidebar-collapsed .sidebar{padding-inline:.75rem;overflow-x:hidden}body.sidebar-collapsed .brand{justify-content:center;gap:0;margin-bottom:1.5rem}body.sidebar-collapsed .brand span,body.sidebar-collapsed .physician-mini > div:last-child,body.sidebar-collapsed .sidebar-collapse span,body.sidebar-collapsed .duty-card{display:none}body.sidebar-collapsed .brand img,body.sidebar-collapsed .avatar{width:48px;height:48px}body.sidebar-collapsed .physician-mini{grid-template-columns:1fr;justify-items:center;margin-bottom:1rem}body.sidebar-collapsed .sidebar-collapse{width:48px;margin-inline:auto}body.sidebar-collapsed .nav-link{justify-content:center;gap:0;padding-inline:.6rem;font-size:0}body.sidebar-collapsed .nav-link i{width:auto;font-size:1.45rem}body.sidebar-collapsed .nav-badge{position:absolute;top:5px;right:4px;min-width:18px;height:18px;margin-left:0;padding:0 .25rem;font-size:.62rem}
        .main{min-width:0;padding:1.45rem 1.6rem}.topbar{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:start;gap:1.2rem;margin-bottom:1.2rem}.topbar:after{content:"";position:absolute;left:40%;top:-1.2rem;width:min(500px,34vw);height:118px;opacity:.16;background:linear-gradient(180deg,transparent 52%,#2c7141 0);clip-path:polygon(0 72%,13% 58%,20% 61%,25% 33%,31% 61%,47% 41%,58% 64%,72% 43%,84% 60%,100% 68%,100% 100%,0 100%);pointer-events:none}.page-title{position:relative;z-index:1}.page-title h1{margin:0 0 .45rem;font-size:clamp(1.8rem,2.5vw,2.35rem);font-weight:950}.page-title p{margin:0;color:#34426f}.top-actions{position:relative;z-index:2;display:flex;align-items:center;gap:1rem}.bell{position:relative;display:grid;place-items:center;width:48px;height:48px;border:0;background:transparent;color:#172447;font-size:1.6rem}.bell span{position:absolute;top:0;right:0;display:grid;place-items:center;width:24px;height:24px;border-radius:50%;color:#fff;background:var(--green);font-size:.75rem;font-weight:950}.date-box{text-align:right;color:#34426f;font-weight:800}.date-box strong{display:block;color:#111735}.doctor-avatar{display:grid;place-items:center;width:58px;height:58px;border:1px solid var(--line);border-radius:50%;color:#fff;background:linear-gradient(145deg,#ffd0b5,#243452);font-size:1.5rem}
        .followup-layout{display:grid;grid-template-columns:430px minmax(0,1fr) 300px;gap:.85rem}.panel{border:1px solid var(--line);border-radius:10px;background:#fff;box-shadow:var(--shadow)}.list-panel{padding:.9rem}.search-row{display:grid;grid-template-columns:minmax(0,1fr) 96px;gap:.7rem;margin-bottom:1rem}.search-box{position:relative}.search-box input{width:100%;height:44px;padding:0 2.7rem 0 1rem;border:1px solid #d7e0ee;border-radius:7px;background:#fff;outline:none}.search-box i{position:absolute;top:50%;right:1rem;color:#0a1b4f;font-size:1.2rem;transform:translateY(-50%)}.filter-btn{display:flex;align-items:center;justify-content:center;gap:.45rem;border:1px solid #d7e0ee;border-radius:7px;background:#fff;font-weight:950}.tabs{display:flex;gap:.35rem;margin-bottom:.8rem;overflow-x:auto}.tab{padding:.55rem .75rem;border-bottom:2px solid transparent;color:#34426f;font-size:.82rem;font-weight:950;white-space:nowrap}.tab.active{color:var(--green-dark);border-color:var(--green)}
        .request-list{display:grid;gap:.65rem}.request-card{display:grid;grid-template-columns:58px minmax(0,1fr) auto;gap:.75rem;padding:.85rem;border:1px solid #edf1f7;border-radius:9px;background:#fff}.request-card.active{border-color:#9eddb4;background:#f8fffa}.request-card strong{display:block}.id,.request-meta{display:block;color:#34426f;font-size:.82rem}.reason{margin:.45rem 0;color:#071438;font-size:.85rem}.tag{display:inline-grid;place-items:center;width:max-content;padding:.32rem .6rem;border-radius:6px;font-size:.76rem;font-weight:950}.tag.pending{color:#6b21d8;border:1px solid #d9c7ff;background:#f6f0ff}.tag.reopened{color:var(--green-dark);border:1px solid #bde2c8;background:#eefaf1}.tag.awaiting{color:#d86700;border:1px solid #ffd09d;background:#fff5e8}.tag.declined{color:#34426f;border:1px solid #d7e0ee;background:#f5f7fb}.urgent{color:var(--red)}.moderate{color:#d98b00}.nonurgent{color:var(--green-dark)}.emergency{color:var(--red)}.list-footer{display:flex;align-items:center;justify-content:space-between;padding:.9rem .35rem 0;color:#34426f;font-size:.85rem}.refresh-link{color:#071438;font-weight:950}
        .detail-panel{padding:1rem}.patient-head{display:grid;grid-template-columns:64px minmax(0,1fr) auto;gap:.9rem;align-items:center;margin-bottom:1rem}.patient-head h2{margin:0 0 .25rem;font-size:1.05rem;font-weight:950}.patient-head p{margin:0;color:#34426f;font-size:.86rem}.notice{margin-bottom:1rem;padding:.8rem 1rem;border:1px solid #cfe0ff;border-radius:8px;color:#071438;background:#f5f9ff}.section-title{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin:1rem 0 .65rem;font-weight:950}.message-box{max-width:78%;padding:1rem;border:1px solid #dfe6f2;border-radius:8px;line-height:1.55;background:#fff}.message-box time{display:block;margin-top:.8rem;color:#34426f;text-align:right;font-size:.8rem}.full-assessment{min-height:34px;padding:0 .8rem;border:1px solid #bde2c8;border-radius:7px;color:var(--green-dark);background:#eefaf1;font-weight:950}.summary-box{display:grid;grid-template-columns:1fr 1fr;border:1px solid #dfe6f2;border-radius:9px;overflow:hidden}.summary-block{padding:1rem;border-right:1px solid #edf1f7;border-bottom:1px solid #edf1f7}.summary-block:nth-child(2n){border-right:0}.summary-block h3{margin:0 0 .55rem;font-size:.9rem;font-weight:950}.summary-block p,.summary-block ul{margin:0;color:#071438}.outcome{color:var(--green-dark);font-weight:950}.timeline{display:grid;gap:1rem;border-top:1px solid var(--line);padding-top:1rem}.timeline-item{display:grid;grid-template-columns:28px minmax(0,1fr);gap:.8rem;align-items:start}.timeline-icon{display:grid;place-items:center;width:24px;height:24px;border-radius:50%;color:#fff;background:var(--green)}.timeline-icon.blue{background:#1f73e8}.timeline-icon.muted{background:#b7c2d2}
        .right-rail{display:grid;gap:.85rem}.side-panel{padding:1rem}.side-panel h2{margin:0 0 .8rem;font-size:1rem;font-weight:950}.action-card{display:grid;grid-template-columns:40px minmax(0,1fr);gap:.8rem;width:100%;margin-bottom:.8rem;padding:.85rem;border-radius:8px;text-align:left}.action-card i{display:grid;place-items:center;width:32px;height:32px;border-radius:50%;font-size:1.2rem}.action-card strong{display:block}.action-card span{font-size:.85rem;line-height:1.45}.action-card.green{border:1px solid #9eddb4;color:var(--green-dark);background:#f0fbf4}.action-card.blue{border:1px solid #a9c8ff;color:#115bd1;background:#f3f7ff}.action-card.red{border:1px solid #ffaaa9;color:var(--red);background:#fff4f3}.info-list{display:grid;gap:.8rem}.info-row{display:flex;align-items:center;justify-content:space-between;gap:1rem;color:#34426f}.info-row strong{color:#071438;text-align:right}.notes-box{width:100%;min-height:118px;padding:.85rem;border:1px solid #d7e0ee;border-radius:8px;resize:vertical}.note-count{display:block;margin:.45rem 0;color:var(--green-dark);text-align:right}.save-note{display:flex;align-items:center;justify-content:center;width:100%;min-height:44px;border:1px solid #9eddb4;border-radius:8px;color:var(--green-dark);background:#f0fbf4;font-weight:950}.security-note{display:flex;align-items:center;gap:.8rem;margin-top:.85rem;padding:.85rem 1rem;border:1px solid #cfe0ff;border-radius:8px;color:#0b2d75;background:#f5f9ff;font-size:.86rem}
        .menu-toggle,.sidebar-overlay{display:none}@media(max-width:1450px){.followup-layout{grid-template-columns:1fr}.right-rail{grid-template-columns:repeat(3,1fr)}}@media(max-width:1100px){.app-shell,body.sidebar-collapsed .app-shell{grid-template-columns:1fr}.sidebar-collapse{display:none}.menu-toggle{position:fixed;top:1rem;left:1rem;z-index:1100;display:grid;place-items:center;width:48px;height:48px;border:1px solid var(--line);border-radius:12px;color:var(--green-dark);background:#fff;box-shadow:0 10px 24px rgba(24,39,75,.12);font-size:1.55rem}.sidebar-overlay{position:fixed;inset:0;z-index:1050;display:block;background:rgba(7,20,56,.42);opacity:0;pointer-events:none;transition:opacity .2s ease}body.sidebar-open .sidebar-overlay{opacity:1;pointer-events:auto}.sidebar{position:fixed;inset:0 auto 0 0;z-index:1060;width:min(84vw,310px);height:100vh;transform:translateX(-100%);transition:transform .24s ease;box-shadow:12px 0 36px rgba(7,20,56,.18)}body.sidebar-open .sidebar{transform:translateX(0)}.main{padding-top:5rem}.topbar{grid-template-columns:1fr}.topbar:after{left:20%;width:70vw}.top-actions{justify-content:flex-start}.right-rail{grid-template-columns:1fr}}@media(max-width:720px){.main{padding-inline:1rem}.top-actions,.date-box{display:none}.request-card,.patient-head,.summary-box{grid-template-columns:1fr}.message-box{max-width:100%}.list-footer{align-items:flex-start;flex-direction:column}.search-row{grid-template-columns:1fr}}
    </style>
</head>
<body>
    <button class="menu-toggle" type="button" aria-label="Open navigation" aria-controls="physicianSidebar" aria-expanded="false"><i class="bi bi-list"></i></button>
    <div class="app-shell">
        <aside class="sidebar" id="physicianSidebar">
            <a class="brand" href="dashboard.php"><img src="../auth/assets/img/CLSU_Logo.jpg" alt="CLSU logo"><span><strong>CLSU Infirmary</strong>Telemedicine System</span></a>
            <div class="physician-mini"><div class="avatar" aria-hidden="true"><i class="bi bi-person-fill"></i></div><div><h2>Dr. Juan Dela Cruz</h2><p>Physician</p><span class="online">Online</span></div></div>
            <button class="sidebar-collapse" type="button" aria-label="Collapse sidebar" aria-expanded="true"><i class="bi bi-layout-sidebar-inset"></i><span>Collapse</span></button>
            <nav aria-label="Physician navigation">
                <ul class="nav-list">
                    <li><a class="nav-link" href="dashboard.php"><i class="bi bi-house-door"></i> Dashboard</a></li>
                    <li><a class="nav-link" href="consultationinbox.php"><i class="bi bi-inbox"></i> Consultation Inbox <span class="nav-badge">8</span></a></li>
                    <li><a class="nav-link" href="activeconsultation.php"><i class="bi bi-clipboard2-pulse"></i> Active Consultations <span class="nav-badge">4</span></a></li>
                    <li><a class="nav-link active" href="followup.php"><i class="bi bi-calendar2-check"></i> Follow-up Requests <span class="nav-badge">6</span></a></li>
                    <li><a class="nav-link" href="patientdirect.php"><i class="bi bi-people"></i> Patient Directory</a></li>
                    <li><a class="nav-link" href="consultationhistory.php"><i class="bi bi-card-list"></i> Consultation History</a></li>
                    <li><a class="nav-link" href="notification.php"><i class="bi bi-bell"></i> Notifications <span class="nav-badge">3</span></a></li>
                </ul>
                <ul class="nav-secondary">
                    <li><a class="nav-link" href="profile.php"><i class="bi bi-person"></i> Profile</a></li>
                    <li><a class="nav-link" href="#"><i class="bi bi-gear"></i> Settings</a></li>
                </ul>
            </nav>
            <section class="duty-card">
                <header><span><i class="bi bi-clock me-2"></i>On Duty</span><i class="bi bi-pencil"></i></header>
                <p>08:00 AM - 04:00 PM</p>
                <p>May 16, 2025 (Friday)</p>
            </section>
            <a class="nav-link logout-link" href="../auth/index.php"><i class="bi bi-box-arrow-left"></i> Logout</a>
        </aside>

        <main class="main">
            <header class="topbar">
                <div class="page-title"><h1>Follow-up Requests</h1><p>Manage patient follow-up or re-engagement requests from completed consultations.</p></div>
                <div class="top-actions"><button class="bell" type="button" aria-label="Notifications"><i class="bi bi-bell"></i><span>3</span></button><div class="date-box"><strong>May 16, 2025</strong><span>Friday, 10:36 AM</span></div><span class="doctor-avatar"><i class="bi bi-person-fill"></i></span><i class="bi bi-chevron-down"></i></div>
            </header>

            <div class="followup-layout">
                <section class="panel list-panel" aria-label="Follow-up request list">
                    <div class="search-row"><label class="search-box"><input type="search" placeholder="Search patient or ID..."><i class="bi bi-search"></i></label><button class="filter-btn" type="button"><i class="bi bi-funnel"></i> Filter</button></div>
                    <div class="tabs"><span class="tab active">All (6)</span><span class="tab">Pending Review (4)</span><span class="tab">Reopened (1)</span><span class="tab">Completed (1)</span><span class="tab">Declined (0)</span></div>
                    <div class="request-list">
                        <article class="request-card active"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Maria Dela Cruz</strong><span class="id">ID: 2025-00123 &nbsp; &bull; &nbsp; 20 yrs &nbsp; &bull; &nbsp; Female</span><p class="urgent fw-bold">Level 2 - Urgent</p><p class="reason"><b>Reason:</b> My fever returned after taking the medication.</p><p class="request-meta"><i class="bi bi-calendar2-week me-1"></i>Last Consult: May 12, 2025</p></div><div class="text-end"><span class="tag pending">Pending Review</span><p class="request-meta mt-5">Today, 09:45 AM</p></div></article>
                        <article class="request-card"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Juan Miguel Santos</strong><span class="id">ID: 2025-00118 &nbsp; &bull; &nbsp; 24 yrs &nbsp; &bull; &nbsp; Male</span><p class="moderate fw-bold">Level 3 - Moderate</p><p class="reason"><b>Reason:</b> Cough is getting worse and difficult to sleep.</p><p class="request-meta"><i class="bi bi-calendar2-week me-1"></i>Last Consult: May 10, 2025</p></div><div class="text-end"><span class="tag pending">Pending Review</span><p class="request-meta mt-5">Yesterday, 04:15 PM</p></div></article>
                        <article class="request-card"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Angela Reyes</strong><span class="id">ID: 2025-00120 &nbsp; &bull; &nbsp; 22 yrs &nbsp; &bull; &nbsp; Female</span><p class="nonurgent fw-bold">Level 4 - Non-urgent</p><p class="reason"><b>Reason:</b> Follow-up for allergy check.</p><p class="request-meta"><i class="bi bi-calendar2-week me-1"></i>Last Consult: May 14, 2025</p></div><div class="text-end"><span class="tag reopened">Reopened</span><p class="request-meta mt-5">May 15, 2025, 11:20 AM</p></div></article>
                        <article class="request-card"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Pedro Garcia</strong><span class="id">ID: 2025-00115 &nbsp; &bull; &nbsp; 45 yrs &nbsp; &bull; &nbsp; Male</span><p class="emergency fw-bold">Level 1 - Emergency</p><p class="reason"><b>Reason:</b> Still experiencing chest pain.</p><p class="request-meta"><i class="bi bi-calendar2-week me-1"></i>Last Consult: May 11, 2025</p></div><div class="text-end"><span class="tag awaiting">Awaiting Your Review</span><p class="request-meta mt-5">May 14, 2025, 08:30 PM</p></div></article>
                        <article class="request-card"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Katrina Lopez</strong><span class="id">ID: 2025-00121 &nbsp; &bull; &nbsp; 19 yrs &nbsp; &bull; &nbsp; Female</span><p class="nonurgent fw-bold">Level 4 - Non-urgent</p><p class="reason"><b>Reason:</b> Need another medical certificate.</p><p class="request-meta"><i class="bi bi-calendar2-week me-1"></i>Last Consult: May 09, 2025</p></div><div class="text-end"><span class="tag declined">Declined</span><p class="request-meta mt-5">May 13, 2025, 02:10 PM</p></div></article>
                        <article class="request-card"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><strong>Kevin Lopez</strong><span class="id">ID: 2025-00125 &nbsp; &bull; &nbsp; 23 yrs &nbsp; &bull; &nbsp; Male</span><p class="moderate fw-bold">Level 3 - Moderate</p><p class="reason"><b>Reason:</b> Follow-up for stomach pain.</p><p class="request-meta"><i class="bi bi-calendar2-week me-1"></i>Last Consult: May 12, 2025</p></div><div class="text-end"><span class="tag pending">Pending Review</span><p class="request-meta mt-5">May 13, 2025, 09:10 PM</p></div></article>
                    </div>
                    <div class="list-footer"><span>Showing 1 to 6 of 6 requests</span><a class="refresh-link" href="#"><i class="bi bi-arrow-clockwise"></i> Refresh</a></div>
                </section>

                <section class="panel detail-panel" aria-label="Selected follow-up request details">
                    <header class="patient-head"><span class="mini-avatar"><i class="bi bi-person-fill"></i></span><div><h2>Maria Dela Cruz</h2><p>ID: 2025-00123 &nbsp; &bull; &nbsp; 20 yrs &nbsp; &bull; &nbsp; Female &nbsp; &bull; &nbsp; 0912 345 6789</p></div><span class="tag pending">Pending Review</span></header>
                    <div class="notice"><i class="bi bi-info-circle me-2 text-primary"></i>Patient is requesting follow-up for a previously completed consultation.</div>
                    <div><div class="section-title">Patient Follow-up Message</div><div class="message-box">Good morning doctor. My fever returned again last night after taking the medication. I also still have body weakness.<time>Today, 09:45 AM</time></div></div>
                    <div><div class="section-title"><span>Previous Consultation Summary (May 12, 2025)</span><button class="full-assessment" type="button"><i class="bi bi-link-45deg me-1"></i>View Full Consultation</button></div><div class="summary-box"><div class="summary-block"><h3>Chief Concern</h3><p>Fever, sore throat, body weakness</p><h3 class="mt-3">Triage Level</h3><p class="urgent fw-bold">Level 2 - Urgent</p></div><div class="summary-block"><h3>Advice / Treatment</h3><ul><li>Paracetamol 500mg every 8 hours</li><li>Drink plenty of fluids</li><li>Rest and monitor temperature</li></ul></div><div class="summary-block"><h3>Diagnosis / Impression</h3><p>Acute Upper Respiratory Infection</p></div><div class="summary-block"><h3>Outcome</h3><p class="outcome">Completed</p></div></div></div>
                    <div><div class="section-title">Consultation Timeline</div><div class="timeline"><div class="timeline-item"><span class="timeline-icon"><i class="bi bi-check-lg"></i></span><div><strong>May 12, 2025 &nbsp; &bull; &nbsp; 10:20 AM</strong><br>Consultation completed by Dr. Juan Dela Cruz</div></div><div class="timeline-item"><span class="timeline-icon blue"><i class="bi bi-chat-dots"></i></span><div><strong>May 16, 2025 &nbsp; &bull; &nbsp; 09:45 AM</strong><br>Patient requested a follow-up</div></div><div class="timeline-item"><span class="timeline-icon muted"><i class="bi bi-clock"></i></span><div><strong>May 16, 2025 &nbsp; &bull; &nbsp; 10:28 AM</strong><br>Pending review</div></div></div></div>
                </section>

                <aside class="right-rail">
                    <section class="panel side-panel"><h2>Request Actions</h2><p class="text-muted mb-2">Choose the appropriate action for this follow-up request.</p><button class="action-card green" type="button"><i class="bi bi-arrow-clockwise"></i><span><strong>Reopen Consultation</strong>Continue the conversation with the patient.</span></button><button class="action-card blue" type="button"><i class="bi bi-info-circle"></i><span><strong>Request More Information</strong>Ask the patient for additional details before deciding.</span></button><button class="action-card red" type="button"><i class="bi bi-x-circle"></i><span><strong>Decline Request</strong>Decline this follow-up request with reason.</span></button></section>
                    <section class="panel side-panel"><h2>Request Information</h2><div class="info-list"><div class="info-row"><span>Follow-up Count</span><strong>1</strong></div><div class="info-row"><span>Total Consultations</span><strong>1</strong></div><div class="info-row"><span>Last Consultation</span><strong>May 12, 2025</strong></div><div class="info-row"><span>Requested At</span><strong>May 16, 2025, 09:45 AM</strong></div><div class="info-row"><span>Assigned To</span><strong><i class="bi bi-person me-1"></i>Dr. Juan Dela Cruz</strong></div></div></section>
                    <section class="panel side-panel"><h2>Notes</h2><textarea class="notes-box" placeholder="Add a note about this follow-up request..."></textarea><span class="note-count">0/250</span><button class="save-note" type="button"><i class="bi bi-bookmark me-2"></i>Save Note</button></section>
                </aside>
            </div>

            <div class="security-note"><i class="bi bi-lock text-primary"></i>Only authorized medical staff can review and manage follow-up requests.</div>
        </main>
    </div>
    <div class="sidebar-overlay" data-close-sidebar></div>
    <script>
        const menuToggle=document.querySelector(".menu-toggle");
        const sidebarCollapse=document.querySelector(".sidebar-collapse");
        const sidebarOverlay=document.querySelector(".sidebar-overlay");
        const sidebarLinks=document.querySelectorAll(".sidebar .nav-link,.sidebar .brand");
        const setSidebar=(isOpen)=>{document.body.classList.toggle("sidebar-open",isOpen);menuToggle.setAttribute("aria-expanded",String(isOpen));menuToggle.setAttribute("aria-label",isOpen?"Close navigation":"Open navigation")};
        menuToggle.addEventListener("click",()=>setSidebar(!document.body.classList.contains("sidebar-open")));
        const setSidebarCollapsed=(isCollapsed)=>{document.body.classList.toggle("sidebar-collapsed",isCollapsed);sidebarCollapse.setAttribute("aria-expanded",String(!isCollapsed));sidebarCollapse.setAttribute("aria-label",isCollapsed?"Expand sidebar":"Collapse sidebar");sidebarCollapse.querySelector("span").textContent=isCollapsed?"Expand":"Collapse"};
        sidebarCollapse.addEventListener("click",()=>setSidebarCollapsed(!document.body.classList.contains("sidebar-collapsed")));
        sidebarOverlay.addEventListener("click",()=>setSidebar(false));
        sidebarLinks.forEach((link)=>link.addEventListener("click",()=>setSidebar(false)));
        document.addEventListener("keydown",(event)=>{if(event.key==="Escape")setSidebar(false)});
    </script>
</body>
</html>
